/**
 * Static map of well-known Korean merchant names to canonical category IDs.
 * Category IDs follow the taxonomy defined in packages/rules/data/categories.yaml.
 * Higher-specificity matches take priority during lookup.
 */
export const MERCHANT_KEYWORDS: Record<string, string> = {
  // ── 카페 / 커피 ──
  '스타벅스': 'dining.cafe',
  'starbucks': 'dining.cafe',
  '투썸플레이스': 'dining.cafe',
  'twosome': 'dining.cafe',
  '이디야': 'dining.cafe',
  '빽다방': 'dining.cafe',
  '메가커피': 'dining.cafe',
  '메가MGC': 'dining.cafe',
  '컴포즈커피': 'dining.cafe',
  '할리스': 'dining.cafe',
  '폴바셋': 'dining.cafe',
  '커피빈': 'dining.cafe',
  'coffee bean': 'dining.cafe',
  '파스쿠찌': 'dining.cafe',
  '더벤티': 'dining.cafe',
  '카페베네': 'dining.cafe',
  '탐앤탐스': 'dining.cafe',
  '엔제리너스': 'dining.cafe',
  '블루보틀': 'dining.cafe',
  '커피스미스': 'dining.cafe',
  '매머드커피': 'dining.cafe',
  '공차': 'dining.cafe',
  '쥬시': 'dining.cafe',
  '앤티앤스': 'dining.cafe',
  '달콤커피': 'dining.cafe',
  '커핀그루나루': 'dining.cafe',
  '드롭탑': 'dining.cafe',
  '카페꼼마': 'dining.cafe',
  '빈스빈스': 'dining.cafe',
  '보나비': 'dining.cafe',
  '커피나무': 'dining.cafe',
  '토프레소': 'dining.cafe',
  '셀렉토커피': 'dining.cafe',
  '더카페': 'dining.cafe',
  '카페띠아모': 'dining.cafe',
  '죠스커피': 'dining.cafe',
  '감성커피': 'dining.cafe',
  '디저트39': 'dining.cafe',
  '와플대학': 'dining.cafe',
  '카페인': 'dining.cafe',
  '더착한커피': 'dining.cafe',
  '커피에반하다': 'dining.cafe',
  '그라찌에': 'dining.cafe',
  '요거프레소': 'dining.cafe',
  '밀크홀': 'dining.cafe',
  '카페드파리': 'dining.cafe',
  '바나프레소': 'dining.cafe',
  '설렘카페': 'dining.cafe',
  '더리터': 'dining.cafe',
  '빈브라더스': 'dining.cafe',
  '프릳츠': 'dining.cafe',
  '센터커피': 'dining.cafe',
  '어니언': 'dining.cafe',
  '테라로사': 'dining.cafe',
  '모모스커피': 'dining.cafe',
  '나무사이로': 'dining.cafe',
  '루프트커피': 'dining.cafe',
  '펠트커피': 'dining.cafe',
  '커피리브레': 'dining.cafe',
  '핸드드립': 'dining.cafe',
  '카페봄봄': 'dining.cafe',
  '하삼동커피': 'dining.cafe',
  '만랩커피': 'dining.cafe',
  '스무디킹': 'dining.cafe',
  '쥬씨': 'dining.cafe',
  '버블티': 'dining.cafe',
  '타이거슈가': 'dining.cafe',
  '밀크티': 'dining.cafe',
  '공차코리아': 'dining.cafe',
  '팔공티': 'dining.cafe',
  '차시음': 'dining.cafe',
  '오설록': 'dining.cafe',
  '티하우스': 'dining.cafe',
  '보이차': 'dining.cafe',

  // ── 베이커리 / 디저트 ──
  '파리바게뜨': 'dining.cafe',
  '뚜레쥬르': 'dining.cafe',
  '던킨': 'dining.cafe',
  '크리스피크림': 'dining.cafe',
  '배스킨라빈스': 'dining.cafe',
  '설빙': 'dining.cafe',
  '성심당': 'dining.cafe',
  '나뚜루': 'dining.cafe',
  '홍루이젠': 'dining.cafe',
  '삼송빵집': 'dining.cafe',
  '이성당': 'dining.cafe',
  '브레댄코': 'dining.cafe',
  '뺑드빠빠': 'dining.cafe',
  '몽슈슈': 'dining.cafe',
  '아우어베이커리': 'dining.cafe',
  '밀도': 'dining.cafe',
  '노티드': 'dining.cafe',
  '런던베이글뮤지엄': 'dining.cafe',
  '하겐다즈': 'dining.cafe',
  '콜드스톤': 'dining.cafe',
  '젤라또': 'dining.cafe',
  '소프트크림': 'dining.cafe',
  '도넛': 'dining.cafe',
  '마카롱': 'dining.cafe',
  '크로플': 'dining.cafe',
  '약과': 'dining.cafe',

  // ── 패스트푸드 ──
  '맥도날드': 'dining.fast_food',
  'mcdonald': 'dining.fast_food',
  '버거킹': 'dining.fast_food',
  'burger king': 'dining.fast_food',
  '롯데리아': 'dining.fast_food',
  '맘스터치': 'dining.fast_food',
  'kfc': 'dining.fast_food',
  '서브웨이': 'dining.fast_food',
  'subway': 'dining.fast_food',
  '파파이스': 'dining.fast_food',
  '노브랜드버거': 'dining.fast_food',
  '쉐이크쉑': 'dining.fast_food',
  '파이브가이즈': 'dining.fast_food',
  '이삭토스트': 'dining.fast_food',
  '쉑쉑': 'dining.fast_food',
  '치폴레': 'dining.fast_food',
  '타코벨': 'dining.fast_food',
  '푸드코트': 'dining.fast_food',
  '분식': 'dining.fast_food',
  '떡볶이': 'dining.fast_food',
  '김밥': 'dining.fast_food',
  '라면': 'dining.fast_food',
  '핫도그': 'dining.fast_food',
  '웬디스': 'dining.fast_food',
  '크라이치즈버거': 'dining.fast_food',
  '다운타우너': 'dining.fast_food',
  '프랭크버거': 'dining.fast_food',
  '수제버거': 'dining.fast_food',
  '쉑버거': 'dining.fast_food',
  '신전떡볶이': 'dining.fast_food',
  '죠스떡볶이': 'dining.fast_food',
  '응급실떡볶이': 'dining.fast_food',
  '두끼떡볶이': 'dining.fast_food',
  '청년다방': 'dining.fast_food',
  '토스트': 'dining.fast_food',
  '고봉민김밥': 'dining.fast_food',
  '바르다김선생': 'dining.fast_food',

  // ── 치킨 / 피자 ──
  '교촌치킨': 'dining.delivery',
  'bbq치킨': 'dining.delivery',
  '네네치킨': 'dining.delivery',
  '굽네치킨': 'dining.delivery',
  'bhc': 'dining.delivery',
  '또래오래': 'dining.delivery',
  '호식이두마리': 'dining.delivery',
  '처갓집': 'dining.delivery',
  '푸라닭': 'dining.delivery',
  '도미노피자': 'dining.delivery',
  'domino': 'dining.delivery',
  '피자헛': 'dining.delivery',
  'pizza hut': 'dining.delivery',
  '미스터피자': 'dining.delivery',
  '피자알볼로': 'dining.delivery',
  '파파존스': 'dining.delivery',
  '60계치킨': 'dining.delivery',
  '자담치킨': 'dining.delivery',
  '페리카나': 'dining.delivery',
  '불닭발': 'dining.delivery',
  '피자나라': 'dining.delivery',
  '7번가피자': 'dining.delivery',
  '청년피자': 'dining.delivery',
  '반올림피자': 'dining.delivery',
  '오구피자': 'dining.delivery',
  '족발야시장': 'dining.delivery',
  '놀부족발': 'dining.delivery',
  '보쌈마을': 'dining.delivery',
  '맘스치킨': 'dining.delivery',
  '지코바치킨': 'dining.delivery',
  '바른치킨': 'dining.delivery',
  '노랑통닭': 'dining.delivery',
  '멕시카나치킨': 'dining.delivery',
  '치킨매니아': 'dining.delivery',
  '후라이드참잘하는집': 'dining.delivery',
  '피자마루': 'dining.delivery',
  '고피자': 'dining.delivery',
  '피자스쿨': 'dining.delivery',
  '알볼로': 'dining.delivery',
  '보스치킨': 'dining.delivery',
  '당신은지금치킨이': 'dining.delivery',
  '신포닭강정': 'dining.delivery',
  '장모족발': 'dining.delivery',
  '원조쭈꾸미': 'dining.delivery',
  '홍콩반점': 'dining.delivery',

  // ── 음식 배달 ──
  '배달의민족': 'dining.delivery',
  '배민': 'dining.delivery',
  '요기요': 'dining.delivery',
  '쿠팡이츠': 'dining.delivery',
  '땡겨요': 'dining.delivery',
  '배민원': 'dining.delivery',
  '배민라이더스': 'dining.delivery',
  '배달특급': 'dining.delivery',
  '위메프오': 'dining.delivery',
  '카카오톡주문하기': 'dining.delivery',

  // ── 외식 체인 / 일반 음식점 ──
  '아웃백': 'dining.restaurant',
  'outback': 'dining.restaurant',
  '빕스': 'dining.restaurant',
  'vips': 'dining.restaurant',
  '애슐리': 'dining.restaurant',
  '매드포갈릭': 'dining.restaurant',
  '한솥': 'dining.restaurant',
  '본죽': 'dining.restaurant',
  '김밥천국': 'dining.restaurant',
  '김가네': 'dining.restaurant',
  '놀부': 'dining.restaurant',
  '더본코리아': 'dining.restaurant',
  '새마을식당': 'dining.restaurant',
  '백년옥': 'dining.restaurant',
  '원할머니보쌈': 'dining.restaurant',
  '한신포차': 'dining.restaurant',
  '이차돌': 'dining.restaurant',
  '하남돼지집': 'dining.restaurant',
  '명륜진사갈비': 'dining.restaurant',
  '황소곱창': 'dining.restaurant',
  '청기와타운': 'dining.restaurant',
  '삼겹살': 'dining.restaurant',
  '본가': 'dining.restaurant',
  '청기와': 'dining.restaurant',
  '강남면옥': 'dining.restaurant',
  '순대실록': 'dining.restaurant',
  '김치찌개': 'dining.restaurant',
  '설렁탕': 'dining.restaurant',
  '냉면': 'dining.restaurant',
  '칼국수': 'dining.restaurant',
  '보쌈': 'dining.restaurant',
  '족발': 'dining.restaurant',
  '불고기': 'dining.restaurant',
  '갈비': 'dining.restaurant',
  '소고기': 'dining.restaurant',
  '돼지고기': 'dining.restaurant',
  '비빔밥': 'dining.restaurant',
  '돈까스': 'dining.restaurant',
  '우동': 'dining.restaurant',
  '라멘': 'dining.restaurant',
  '초밥': 'dining.restaurant',
  '회전초밥': 'dining.restaurant',
  '중국집': 'dining.restaurant',
  '짜장면': 'dining.restaurant',
  '짬뽕': 'dining.restaurant',
  '탕수육': 'dining.restaurant',
  '양꼬치': 'dining.restaurant',
  '마라탕': 'dining.restaurant',
  '마라샹궈': 'dining.restaurant',
  '샤브샤브': 'dining.restaurant',
  '쌀국수': 'dining.restaurant',
  '태국음식': 'dining.restaurant',
  '인도커리': 'dining.restaurant',
  '일본식당': 'dining.restaurant',
  '뷔페': 'dining.restaurant',
  '연회장': 'dining.restaurant',
  '웨딩홀': 'dining.restaurant',
  '백종원': 'dining.restaurant',
  '홍콩반점0410': 'dining.restaurant',
  '역전우동': 'dining.restaurant',
  '미소야': 'dining.restaurant',
  '하코야': 'dining.restaurant',
  '스시로': 'dining.restaurant',
  '쿠라스시': 'dining.restaurant',
  '가쯔야': 'dining.restaurant',
  '정돈': 'dining.restaurant',
  '사보텐': 'dining.restaurant',
  '규카츠': 'dining.restaurant',
  '고메레스토랑': 'dining.restaurant',
  '정육식당': 'dining.restaurant',
  '곱창': 'dining.restaurant',
  '대창': 'dining.restaurant',
  '막창': 'dining.restaurant',
  '순대국': 'dining.restaurant',
  '해장국': 'dining.restaurant',
  '감자탕': 'dining.restaurant',
  '뼈해장국': 'dining.restaurant',
  '부대찌개': 'dining.restaurant',
  '두부': 'dining.restaurant',
  '순두부찌개': 'dining.restaurant',
  '된장찌개': 'dining.restaurant',
  '국밥': 'dining.restaurant',
  '돼지국밥': 'dining.restaurant',
  '소머리국밥': 'dining.restaurant',
  '추어탕': 'dining.restaurant',
  '삼계탕': 'dining.restaurant',
  '닭한마리': 'dining.restaurant',
  '닭볶음탕': 'dining.restaurant',
  '찜닭': 'dining.restaurant',
  '갈비찜': 'dining.restaurant',
  '쭈꾸미': 'dining.restaurant',
  '낙곱새': 'dining.restaurant',
  '전골': 'dining.restaurant',
  '곰탕': 'dining.restaurant',
  '갈비탕': 'dining.restaurant',
  '육개장': 'dining.restaurant',
  '떡갈비': 'dining.restaurant',
  '생선구이': 'dining.restaurant',
  '회': 'dining.restaurant',
  '횟집': 'dining.restaurant',
  '스시': 'dining.restaurant',
  '사시미': 'dining.restaurant',
  '이자카야': 'dining.restaurant',
  '오마카세': 'dining.restaurant',
  '카이센동': 'dining.restaurant',
  '규동': 'dining.restaurant',
  '덮밥': 'dining.restaurant',
  '카레': 'dining.restaurant',
  '파스타': 'dining.restaurant',
  '스테이크': 'dining.restaurant',
  '브런치카페': 'dining.restaurant',
  '그릴': 'dining.restaurant',
  '바베큐': 'dining.restaurant',
  '치즈': 'dining.restaurant',
  '퐁듀': 'dining.restaurant',
  '한정식': 'dining.restaurant',
  '백반': 'dining.restaurant',
  '쌈밥': 'dining.restaurant',
  '보리밥': 'dining.restaurant',
  '닭갈비': 'dining.restaurant',
  '춘천닭갈비': 'dining.restaurant',
  '묵은지김치찜': 'dining.restaurant',
  '아구찜': 'dining.restaurant',
  '해물탕': 'dining.restaurant',
  '대게': 'dining.restaurant',
  '킹크랩': 'dining.restaurant',
  '랍스타': 'dining.restaurant',
  '조개구이': 'dining.restaurant',
  '포장마차': 'dining.restaurant',
  '술집': 'dining.restaurant',
  '호프': 'dining.restaurant',
  '치맥': 'dining.restaurant',
  '이자까야': 'dining.restaurant',
  '와인바': 'dining.restaurant',
  '칵테일바': 'dining.restaurant',
  '펍': 'dining.restaurant',
  '하이볼': 'dining.restaurant',
  '더플레이스': 'dining.restaurant',
  '빕스프리미어': 'dining.restaurant',
  '토다이': 'dining.restaurant',
  '계절밥상': 'dining.restaurant',
  '올반': 'dining.restaurant',
  '자연별곡': 'dining.restaurant',
  '풀잎채': 'dining.restaurant',
  '봉추찜닭': 'dining.restaurant',
  '유가네닭갈비': 'dining.restaurant',
  '원조삼계탕': 'dining.restaurant',
  '처음처럼': 'dining.restaurant',
  '참이슬': 'dining.restaurant',
  '채선당': 'dining.restaurant',
  '돈수백': 'dining.restaurant',
  '진진': 'dining.restaurant',

  // ── 대형마트 / 식료품 ──
  '이마트': 'grocery.supermarket',
  'emart': 'grocery.supermarket',
  '이마트에브리데이': 'grocery.supermarket',
  '홈플러스': 'grocery.supermarket',
  'homeplus': 'grocery.supermarket',
  '롯데마트': 'grocery.supermarket',
  '롯데슈퍼': 'grocery.supermarket',
  '코스트코': 'grocery.supermarket',
  'costco': 'grocery.supermarket',
  '농협하나로마트': 'grocery.supermarket',
  '하나로클럽': 'grocery.supermarket',
  '노브랜드': 'grocery.supermarket',
  '트레이더스': 'grocery.supermarket',
  '메가마트': 'grocery.supermarket',
  'ssg': 'grocery.supermarket',
  '하나로마트': 'grocery.supermarket',
  '농산물시장': 'grocery.supermarket',
  '수산시장': 'grocery.supermarket',
  '축산물': 'grocery.supermarket',
  '청과물': 'grocery.supermarket',
  '식자재마트': 'grocery.supermarket',
  'GS더프레시': 'grocery.supermarket',
  '신세계푸드': 'grocery.supermarket',
  '킴스클럽': 'grocery.supermarket',
  '빅마트': 'grocery.supermarket',
  '세이브존': 'grocery.supermarket',
  '한화갤러리아슈퍼': 'grocery.supermarket',
  '농수산물도매시장': 'grocery.supermarket',
  '수산물시장': 'grocery.supermarket',
  '정육점': 'grocery.supermarket',
  '반찬가게': 'grocery.supermarket',
  '반찬전문점': 'grocery.supermarket',
  '진저마켓': 'grocery.supermarket',

  // ── 전통시장 ──
  '시장': 'grocery.traditional_market',
  '재래시장': 'grocery.traditional_market',
  '전통시장': 'grocery.traditional_market',
  '장터': 'grocery.traditional_market',
  '남대문시장': 'grocery.traditional_market',
  '동대문시장': 'grocery.traditional_market',
  '광장시장': 'grocery.traditional_market',
  '통인시장': 'grocery.traditional_market',
  '망원시장': 'grocery.traditional_market',
  '노량진수산시장': 'grocery.traditional_market',
  '가락시장': 'grocery.traditional_market',

  // ── 온라인 장보기 ──
  '마켓컬리': 'grocery.online_grocery',
  '컬리': 'grocery.online_grocery',
  '오아시스마켓': 'grocery.online_grocery',
  'b마트': 'grocery.online_grocery',
  '쿠팡로켓프레시': 'grocery.online_grocery',
  '네이버장보기': 'grocery.online_grocery',
  '헬로네이처': 'grocery.online_grocery',
  '쿠팡프레시': 'grocery.online_grocery',
  'SSG닷컴': 'grocery.online_grocery',
  '이마트몰': 'grocery.online_grocery',
  '홈플러스온라인': 'grocery.online_grocery',
  '롯데온식품': 'grocery.online_grocery',
  '쓱닷컴': 'grocery.online_grocery',
  '로켓프레시': 'grocery.online_grocery',
  '마켓보로': 'grocery.online_grocery',
  '정육각': 'grocery.online_grocery',
  '미트박스': 'grocery.online_grocery',
  '오늘회': 'grocery.online_grocery',

  // ── 편의점 ──
  'cu': 'convenience_store',
  'gs25': 'convenience_store',
  '세븐일레븐': 'convenience_store',
  '7-eleven': 'convenience_store',
  '7eleven': 'convenience_store',
  '미니스톱': 'convenience_store',
  '이마트24': 'convenience_store',
  '씨유': 'convenience_store',
  '지에스25': 'convenience_store',
  '스토리웨이': 'convenience_store',
  '위드미': 'convenience_store',
  '편의점': 'convenience_store',

  // ── 온라인 쇼핑 ──
  '쿠팡': 'online_shopping',
  'coupang': 'online_shopping',
  '네이버쇼핑': 'online_shopping',
  '네이버페이': 'online_shopping',
  '11번가': 'online_shopping',
  'g마켓': 'online_shopping',
  'gmarket': 'online_shopping',
  '옥션': 'online_shopping',
  'auction': 'online_shopping',
  '위메프': 'online_shopping',
  '티몬': 'online_shopping',
  '인터파크': 'online_shopping',
  '카카오쇼핑': 'online_shopping',
  '알리익스프레스': 'online_shopping',
  'aliexpress': 'online_shopping',
  '아마존': 'online_shopping',
  'amazon': 'online_shopping',
  '테무': 'online_shopping',
  'temu': 'online_shopping',
  '쉬인': 'online_shopping',
  'shein': 'online_shopping',
  '올리브영온라인': 'online_shopping',
  '카카오톡스토어': 'online_shopping',
  '톡딜': 'online_shopping',
  '직방': 'online_shopping',
  '네이버스토어': 'online_shopping',
  '카카오톡선물하기': 'online_shopping',
  '스마트스토어': 'online_shopping',
  '이베이': 'online_shopping',
  'ebay': 'online_shopping',
  '소셜커머스': 'online_shopping',
  '중고나라': 'online_shopping',
  '당근마켓': 'online_shopping',
  '번개장터': 'online_shopping',
  '아이디어스': 'online_shopping',
  '핸드메이드': 'online_shopping',
  '지마켓글로벌': 'online_shopping',
  'SSG': 'online_shopping',
  '롯데온': 'online_shopping',
  '하이버': 'online_shopping',
  '오늘의집': 'online_shopping',
  '쿠팡로켓배송': 'online_shopping',
  '네이버페이결제': 'online_shopping',
  '카카오페이결제': 'online_shopping',
  '토스페이먼츠': 'online_shopping',
  '페이코': 'online_shopping',
  '삼성페이': 'online_shopping',
  '애플페이': 'online_shopping',
  '알리바바': 'online_shopping',
  'alibaba': 'online_shopping',
  '아이허브': 'online_shopping',
  'iherb': 'online_shopping',
  '큐텐': 'online_shopping',
  'qoo10': 'online_shopping',
  '캐치패션': 'online_shopping',
  '발란': 'online_shopping',
  '트렌비': 'online_shopping',
  '머스트잇': 'online_shopping',
  '오퀴즈': 'online_shopping',

  // ── 패션 / 의류 ──
  '무신사': 'fashion',
  'musinsa': 'fashion',
  '에이블리': 'fashion',
  '지그재그': 'fashion',
  '브랜디': 'fashion',
  '29cm': 'fashion',
  'wconcept': 'fashion',
  'W컨셉': 'fashion',
  '더한섬': 'fashion',
  '유니클로': 'fashion',
  'uniqlo': 'fashion',
  '자라': 'fashion',
  'zara': 'fashion',
  'h&m': 'fashion',
  '나이키': 'fashion',
  'nike': 'fashion',
  '아디다스': 'fashion',
  'adidas': 'fashion',
  '뉴발란스': 'fashion',
  'abc마트': 'fashion',
  '크림': 'fashion',
  'kream': 'fashion',
  '탑텐': 'fashion',
  '스파오': 'fashion',
  '8seconds': 'fashion',
  '에잇세컨즈': 'fashion',
  '폴로': 'fashion',
  '랄프로렌': 'fashion',
  '구찌': 'fashion',
  'gucci': 'fashion',
  '루이비통': 'fashion',
  'louis vuitton': 'fashion',
  '샤넬': 'fashion',
  'chanel': 'fashion',
  '프라다': 'fashion',
  'prada': 'fashion',
  '버버리': 'fashion',
  'burberry': 'fashion',
  '발렌시아가': 'fashion',
  'balenciaga': 'fashion',
  '디올': 'fashion',
  'dior': 'fashion',
  '에르메스': 'fashion',
  'hermes': 'fashion',
  '나이키코리아': 'fashion',
  '아디다스코리아': 'fashion',
  '캉골': 'fashion',
  '디스커버리': 'fashion',
  '노스페이스': 'fashion',
  'the north face': 'fashion',
  '파타고니아': 'fashion',
  'patagonia': 'fashion',
  'k2': 'fashion',
  '블랙야크': 'fashion',
  '코오롱스포츠': 'fashion',
  '아이더': 'fashion',
  '데카트론': 'fashion',
  'decathlon': 'fashion',
  '지오다노': 'fashion',
  '갭': 'fashion',
  'gap': 'fashion',
  '망고': 'fashion',
  'mango': 'fashion',
  '마시모두띠': 'fashion',
  '코스': 'fashion',
  '앤아더스토리즈': 'fashion',
  '무인양품': 'fashion',
  '라코스테': 'fashion',
  '타미힐피거': 'fashion',
  '캘빈클라인': 'fashion',
  '게스': 'fashion',
  '리바이스': 'fashion',
  '리복': 'fashion',
  '푸마': 'fashion',
  'puma': 'fashion',
  '휠라': 'fashion',
  'fila': 'fashion',
  '컨버스': 'fashion',
  'converse': 'fashion',
  '반스': 'fashion',
  'vans': 'fashion',
  '스케쳐스': 'fashion',
  'skechers': 'fashion',
  '크록스': 'fashion',
  'crocs': 'fashion',
  '닥터마틴': 'fashion',
  '에코': 'fashion',
  '클락스': 'fashion',
  '미즈노': 'fashion',
  '아식스': 'fashion',
  '호카': 'fashion',
  '온러닝': 'fashion',
  '살로몬': 'fashion',
  'ABC마트': 'fashion',
  '슈마커': 'fashion',
  '풋락커': 'fashion',
  '레스모아': 'fashion',

  // ── 백화점 ──
  '롯데백화점': 'department_store',
  '현대백화점': 'department_store',
  '신세계백화점': 'department_store',
  'shinsegae': 'department_store',
  '갤러리아': 'department_store',
  '에이케이플라자': 'department_store',
  '더현대': 'department_store',
  '신세계': 'department_store',
  '롯데아울렛': 'department_store',
  '현대아울렛': 'department_store',
  'AK플라자': 'department_store',
  'NC백화점': 'department_store',
  '스타필드': 'department_store',
  '더현대서울': 'department_store',
  '현대프리미엄아울렛': 'department_store',
  '신세계아울렛': 'department_store',
  '롯데프리미엄아울렛': 'department_store',
  '하남스타필드': 'department_store',
  '고양스타필드': 'department_store',

  // ── 뷰티 / 화장품 ──
  '올리브영': 'offline_shopping',
  '시코르': 'offline_shopping',
  '롭스': 'offline_shopping',
  '이니스프리': 'offline_shopping',
  '아모레퍼시픽': 'offline_shopping',
  '다이소': 'offline_shopping',
  'daiso': 'offline_shopping',
  '세포라': 'offline_shopping',
  'sephora': 'offline_shopping',
  '에뛰드': 'offline_shopping',
  '미샤': 'offline_shopping',
  '더페이스샵': 'offline_shopping',
  '네이처리퍼블릭': 'offline_shopping',
  '스킨푸드': 'offline_shopping',
  '토니모리': 'offline_shopping',
  '클리오': 'offline_shopping',
  '라네즈': 'offline_shopping',
  '설화수': 'offline_shopping',
  '헤라': 'offline_shopping',
  '맥': 'offline_shopping',
  '에스티로더': 'offline_shopping',
  '랑콤': 'offline_shopping',
  '바비브라운': 'offline_shopping',

  // ── 오프라인 쇼핑 / 리테일 ──
  '아울렛': 'offline_shopping',
  '프리미엄아울렛': 'offline_shopping',
  '홈플러스익스프레스': 'offline_shopping',
  'GS수퍼': 'offline_shopping',
  '오피스디포': 'offline_shopping',
  '모닝글로리': 'offline_shopping',
  '핫트랙스': 'offline_shopping',
  '교보핫트랙스': 'offline_shopping',
  '아트박스': 'offline_shopping',
  '마리떼프랑소와': 'offline_shopping',
  '리빙박스': 'offline_shopping',
  '한샘디자인파크': 'offline_shopping',
  '까사미아': 'offline_shopping',
  '일룸': 'offline_shopping',
  '시몬스': 'offline_shopping',
  '에이스침대': 'offline_shopping',
  '펫프렌즈': 'offline_shopping',
  '바잇미': 'offline_shopping',
  '세탁': 'offline_shopping',
  '크린토피아': 'offline_shopping',
  '런드리고': 'offline_shopping',
  '이케아': 'offline_shopping',
  'ikea': 'offline_shopping',
  '한샘': 'offline_shopping',
  '삼성전자': 'offline_shopping',
  '하이마트': 'offline_shopping',
  '전자랜드': 'offline_shopping',
  '쿠쿠': 'offline_shopping',
  'lg전자': 'offline_shopping',
  '애플': 'offline_shopping',
  'apple': 'offline_shopping',
  '쿠쿠전자': 'offline_shopping',
  '코웨이': 'offline_shopping',
  '다이슨': 'offline_shopping',
  'dyson': 'offline_shopping',
  '필립스': 'offline_shopping',
  '미래와사람': 'offline_shopping',
  '세탁특공대': 'offline_shopping',
  '워시엔조이': 'offline_shopping',
  '코인워시': 'offline_shopping',
  '세탁편의점': 'offline_shopping',
  '꽃집': 'offline_shopping',
  '꽃배달': 'offline_shopping',
  '플라워마켓': 'offline_shopping',
  '안경점': 'offline_shopping',
  '렌즈미': 'offline_shopping',
  '안경매장': 'offline_shopping',
  '시계매장': 'offline_shopping',
  '귀금속': 'offline_shopping',
  '쥬얼리': 'offline_shopping',
  '문구점': 'offline_shopping',
  '바른손': 'offline_shopping',
  '만물상': 'offline_shopping',

  // ── 택시 ──
  '카카오택시': 'taxi',
  '카카오T': 'taxi',
  '카카오모빌리티': 'taxi',
  '타다': 'taxi',
  '우티': 'taxi',
  'ut': 'taxi',
  '아이엠택시': 'taxi',
  '택시': 'taxi',
  '반반택시': 'taxi',
  '마카롱택시': 'taxi',
  '온다택시': 'taxi',
  '티머니고택시': 'taxi',
  '콜택시': 'taxi',
  '모범택시': 'taxi',
  '대리운전': 'taxi',
  '카카오대리': 'taxi',

  // ── 대중교통 ──
  '코레일': 'public_transit',
  'korail': 'public_transit',
  'srt': 'public_transit',
  'ktx': 'public_transit',
  '서울교통공사': 'public_transit',
  '지하철': 'public_transit',
  '버스': 'public_transit',
  '티머니': 'public_transit',
  '캐시비': 'public_transit',
  '레일플러스': 'public_transit',
  '고속버스': 'public_transit',
  '시외버스': 'public_transit',
  '서울시내버스': 'public_transit',
  '경기버스': 'public_transit',
  '인천버스': 'public_transit',
  '대전버스': 'public_transit',
  '부산버스': 'public_transit',
  '광주버스': 'public_transit',
  '대구지하철': 'public_transit',
  '부산지하철': 'public_transit',
  '인천메트로': 'public_transit',
  '공항철도': 'public_transit',
  '신분당선': 'public_transit',
  '의정부경전철': 'public_transit',
  '용인경전철': 'public_transit',
  '김포골드라인': 'public_transit',
  '대구도시철도': 'public_transit',
  '광주도시철도': 'public_transit',
  '대전도시철도': 'public_transit',
  '동해선': 'public_transit',
  '경의중앙선': 'public_transit',
  '수인분당선': 'public_transit',
  '경춘선': 'public_transit',
  '경강선': 'public_transit',
  'GTX': 'public_transit',
  '마을버스': 'public_transit',
  '광역버스': 'public_transit',
  '급행버스': 'public_transit',
  '공항버스': 'public_transit',
  '서울메트로': 'public_transit',
  '한국철도공사': 'public_transit',
  '무궁화호': 'public_transit',
  '새마을호': 'public_transit',
  'ITX': 'public_transit',
  '누리로': 'public_transit',

  // ── 주유 / EV 충전 ──
  'sk에너지': 'fuel',
  'sk주유소': 'fuel',
  'gs칼텍스': 'fuel',
  '현대오일뱅크': 'fuel',
  '에쓰오일': 'fuel',
  's-oil': 'fuel',
  '알뜰주유소': 'fuel',
  'ev충전': 'fuel',
  '충전소': 'fuel',
  '한국전력충전': 'fuel',
  'SK충전소': 'fuel',
  'GS차지': 'fuel',
  '현대EV': 'fuel',
  '기아EV': 'fuel',
  '테슬라슈퍼차저': 'fuel',
  '환경부충전소': 'fuel',
  '해피차저': 'fuel',
  '차지비': 'fuel',
  '에버온': 'fuel',
  '파워큐브': 'fuel',
  '채비': 'fuel',
  '플러그링크': 'fuel',
  '주유소': 'fuel',
  '셀프주유': 'fuel',
  '경유': 'fuel',
  '휘발유': 'fuel',
  'lpg충전소': 'fuel',
  '스타차지': 'fuel',
  '그린차저': 'fuel',
  '소프트베리': 'fuel',
  '한국전기차충전서비스': 'fuel',
  '포스코에너지': 'fuel',
  'SK네트웍스': 'fuel',

  // ── 주차 ──
  '주차': 'parking',
  '주차장': 'parking',
  '파킹클라우드': 'parking',
  '아이파킹': 'parking',
  '모두의주차장': 'parking',
  '아파트주차': 'parking',
  '공영주차장': 'parking',
  '민영주차장': 'parking',
  '카카오T주차': 'parking',
  '네이버주차': 'parking',
  '파킹박': 'parking',
  '파킹스퀘어': 'parking',
  '지하주차장': 'parking',
  '노상주차': 'parking',
  '발렛파킹': 'parking',
  '기계식주차': 'parking',

  // ── 통행료 ──
  '하이패스': 'toll',
  '고속도로': 'toll',
  '한국도로공사': 'toll',
  '통행료': 'toll',
  '유료도로': 'toll',

  // ── 영화 ──
  'cgv': 'movie',
  '롯데시네마': 'movie',
  '메가박스': 'movie',
  'megabox': 'movie',
  '씨네큐': 'movie',
  '프리머스시네마': 'movie',
  '대한극장': 'movie',
  '아이맥스': 'movie',
  'imax': 'movie',
  '씨지브이': 'movie',
  '영화관': 'movie',
  '영화예매': 'movie',
  '독립영화관': 'movie',
  '인디스페이스': 'movie',
  '시네마테크': 'movie',
  '4DX': 'movie',
  '스크린X': 'movie',

  // ── 스트리밍 / 구독 콘텐츠 ──
  '넷플릭스': 'streaming',
  'netflix': 'streaming',
  '유튜브프리미엄': 'streaming',
  'youtube premium': 'streaming',
  'youtube': 'streaming',
  '왓챠': 'streaming',
  '웨이브': 'streaming',
  'wavve': 'streaming',
  '시즌': 'streaming',
  '티빙': 'streaming',
  'tving': 'streaming',
  '디즈니플러스': 'streaming',
  'disney+': 'streaming',
  'disney plus': 'streaming',
  '애플tv': 'streaming',
  'apple tv': 'streaming',
  '스포티파이': 'streaming',
  'spotify': 'streaming',
  '멜론': 'streaming',
  '지니뮤직': 'streaming',
  '플로': 'streaming',
  '벅스': 'streaming',
  '밀리의서재': 'streaming',
  '리디북스': 'streaming',
  '리디': 'streaming',
  '쿠팡플레이': 'streaming',
  'coupang play': 'streaming',
  '아마존프라임': 'streaming',
  '네이버시리즈온': 'streaming',
  '카카오페이지': 'streaming',
  '시리즈': 'streaming',
  '네이버웹툰': 'streaming',
  '카카오웹툰': 'streaming',
  '레진코믹스': 'streaming',
  '탑툰': 'streaming',
  '오디오클립': 'streaming',
  '팟빵': 'streaming',
  '유튜브뮤직': 'streaming',
  'youtube music': 'streaming',
  '바이브': 'streaming',
  '소리바다': 'streaming',
  '네이버뮤직': 'streaming',
  '애플뮤직': 'streaming',
  'apple music': 'streaming',
  '아마존뮤직': 'streaming',
  '오디블': 'streaming',
  'audible': 'streaming',
  '윌라': 'streaming',
  '스토리텔': 'streaming',
  '문피아': 'streaming',
  '조아라': 'streaming',
  '봄툰': 'streaming',
  '코미코': 'streaming',
  '만화경': 'streaming',
  '포켓코믹스': 'streaming',
  '네이버시리즈': 'streaming',
  '라프텔': 'streaming',
  '애니메이트': 'streaming',
  'crunchyroll': 'streaming',
  '파라마운트플러스': 'streaming',
  '피콕': 'streaming',
  'hbo max': 'streaming',
  '맥스': 'streaming',

  // ── 구독 / 멤버십 ──
  '쿠팡로켓와우': 'subscription',
  '네이버플러스멤버십': 'subscription',
  'ssg멤버십': 'subscription',
  '카카오톡이모티콘플러스': 'subscription',
  '배민클럽': 'subscription',
  '요기패스': 'subscription',
  '오늘의집플러스': 'subscription',
  'chatgpt': 'subscription',
  'claude': 'subscription',
  'notion': 'subscription',
  '노션': 'subscription',
  'dropbox': 'subscription',
  'icloud': 'subscription',
  'google one': 'subscription',
  '구글원': 'subscription',
  'adobe': 'subscription',
  '어도비': 'subscription',
  'microsoft 365': 'subscription',

  // ── 게임 / 앱스토어 / 엔터테인먼트 ──
  '구글플레이': 'entertainment',
  'google play': 'entertainment',
  '앱스토어': 'entertainment',
  'apple.com/bill': 'entertainment',
  '넥슨': 'entertainment',
  '엔씨소프트': 'entertainment',
  '넷마블': 'entertainment',
  '카카오게임즈': 'entertainment',
  '스팀': 'entertainment',
  'steam': 'entertainment',
  '플레이스테이션': 'entertainment',
  'playstation': 'entertainment',
  '닌텐도': 'entertainment',
  'nintendo': 'entertainment',
  '볼링장': 'entertainment',
  '당구장': 'entertainment',
  'PC방': 'entertainment',
  'pc방': 'entertainment',
  '피시방': 'entertainment',
  '노래방': 'entertainment',
  '코인노래방': 'entertainment',
  '방탈출': 'entertainment',
  'VR카페': 'entertainment',
  'vr카페': 'entertainment',
  '보드게임카페': 'entertainment',
  '만화카페': 'entertainment',
  '찜질방': 'entertainment',
  '사우나': 'entertainment',
  '목욕탕': 'entertainment',
  '수영장': 'entertainment',
  '테니스장': 'entertainment',
  '배드민턴': 'entertainment',
  '축구장': 'entertainment',
  '야구장': 'entertainment',
  '농구장': 'entertainment',
  '캠핑': 'entertainment',
  '글램핑': 'entertainment',
  '펜션': 'entertainment',
  '헬스장': 'entertainment',
  '피트니스': 'entertainment',
  '요가': 'entertainment',
  '필라테스': 'entertainment',
  '골프': 'entertainment',
  '골프장': 'entertainment',
  '스크린골프': 'entertainment',
  '에버랜드': 'entertainment',
  '롯데월드': 'entertainment',
  '워터파크': 'entertainment',
  '스키장': 'entertainment',
  '놀이공원': 'entertainment',
  '키자니아': 'entertainment',
  '크래프톤': 'entertainment',
  '스마일게이트': 'entertainment',
  '펄어비스': 'entertainment',
  '위메이드': 'entertainment',
  '컴투스': 'entertainment',
  '데브시스터즈': 'entertainment',
  'epic games': 'entertainment',
  '에픽게임즈': 'entertainment',
  'xbox': 'entertainment',
  '엑스박스': 'entertainment',
  'riot games': 'entertainment',
  '라이엇게임즈': 'entertainment',
  '카트라이더': 'entertainment',
  '로블록스': 'entertainment',
  'roblox': 'entertainment',
  '클럽': 'entertainment',
  '라운지': 'entertainment',
  '실내낚시': 'entertainment',
  '낚시터': 'entertainment',
  '승마': 'entertainment',
  '사격장': 'entertainment',
  '실내사격': 'entertainment',
  '짚라인': 'entertainment',
  '번지점프': 'entertainment',
  '서바이벌': 'entertainment',
  '레이싱': 'entertainment',
  '카트': 'entertainment',
  '클라이밍': 'entertainment',
  '실내암벽': 'entertainment',
  '트램폴린': 'entertainment',
  '인라인': 'entertainment',
  '아이스링크': 'entertainment',
  '스케이트장': 'entertainment',
  '서핑': 'entertainment',
  '다이빙': 'entertainment',
  '스쿠버다이빙': 'entertainment',
  '패러글라이딩': 'entertainment',
  '서울랜드': 'entertainment',
  '오션월드': 'entertainment',
  '캐리비안베이': 'entertainment',
  '경주월드': 'entertainment',
  '통도환타지아': 'entertainment',
  '한국민속촌': 'entertainment',
  '아쿠아리움': 'entertainment',
  '동물원': 'entertainment',
  '식물원': 'entertainment',
  '미술관': 'entertainment',
  '박물관': 'entertainment',
  '전시회': 'entertainment',
  '공연장': 'entertainment',
  '콘서트': 'entertainment',
  '뮤지컬': 'entertainment',
  '연극': 'entertainment',
  '오페라': 'entertainment',
  '인터파크티켓': 'entertainment',
  '예스24티켓': 'entertainment',
  '티켓링크': 'entertainment',
  '멜론티켓': 'entertainment',
  '네이버예약': 'entertainment',

  // ── 통신 ──
  'skt': 'telecom',
  'sk텔레콤': 'telecom',
  'kt': 'telecom',
  'lg유플러스': 'telecom',
  'lgu+': 'telecom',
  '알뜰폰': 'telecom',
  '헬로모바일': 'telecom',
  'sk브로드밴드': 'telecom',
  'kt인터넷': 'telecom',
  'lg인터넷': 'telecom',
  'SKT요금': 'telecom',
  'KT요금': 'telecom',
  'LG요금': 'telecom',
  '알뜰통신': 'telecom',
  '프리텔': 'telecom',
  '여유텔레콤': 'telecom',
  '에넥스텔레콤': 'telecom',
  '눝': 'telecom',
  'U+모바일': 'telecom',
  'KT인터넷': 'telecom',
  'SK인터넷': 'telecom',
  '통신요금': 'telecom',
  '핸드폰요금': 'telecom',
  '휴대폰요금': 'telecom',
  '인터넷요금': 'telecom',
  'IPTV': 'telecom',
  '케이블TV': 'telecom',
  '티플러스': 'telecom',
  '마이월드': 'telecom',
  '스노우맨': 'telecom',
  '인스코비': 'telecom',

  // ── 보험 ──
  '삼성화재': 'insurance',
  '현대해상': 'insurance',
  'kb손해보험': 'insurance',
  '메리츠화재': 'insurance',
  '한화생명': 'insurance',
  '삼성생명': 'insurance',
  '교보생명': 'insurance',
  'db손해보험': 'insurance',
  '흥국화재': 'insurance',
  '라이나생명': 'insurance',
  'AXA손해보험': 'insurance',
  'AIG보험': 'insurance',
  '처브보험': 'insurance',
  '동양생명': 'insurance',
  '미래에셋생명': 'insurance',
  '신한생명': 'insurance',
  '농협생명': 'insurance',
  '하나생명': 'insurance',
  'NH손해보험': 'insurance',
  '메리츠화재보험': 'insurance',
  '한화손해보험': 'insurance',
  '롯데손해보험': 'insurance',
  'mg손해보험': 'insurance',
  '푸본현대생명': 'insurance',
  '카카오페이손해보험': 'insurance',
  '토스손해보험': 'insurance',
  '자동차보험': 'insurance',
  '실손보험': 'insurance',
  '생명보험': 'insurance',
  '손해보험': 'insurance',
  '화재보험': 'insurance',
  '운전자보험': 'insurance',
  '여행자보험': 'insurance',

  // ── 병원 / 의료 ──
  '병원': 'hospital',
  '의원': 'hospital',
  '치과': 'hospital',
  '한의원': 'hospital',
  '안과': 'hospital',
  '피부과': 'hospital',
  '정형외과': 'hospital',
  '내과': 'hospital',
  '산부인과': 'hospital',
  '소아과': 'hospital',
  '이비인후과': 'hospital',
  '종합병원': 'hospital',
  '대학병원': 'hospital',
  '의료원': 'hospital',
  '성형외과': 'hospital',
  '비뇨기과': 'hospital',
  '신경외과': 'hospital',
  '재활의학과': 'hospital',
  '정신건강의학과': 'hospital',
  '영상의학과': 'hospital',
  '응급의원': 'hospital',
  '요양병원': 'hospital',
  '검진센터': 'hospital',
  '건강검진': 'hospital',
  '클리닉': 'hospital',
  '외과': 'hospital',
  '흉부외과': 'hospital',
  '심장내과': 'hospital',
  '소화기내과': 'hospital',
  '호흡기내과': 'hospital',
  '신경과': 'hospital',
  '마취통증의학과': 'hospital',
  '진단검사의학과': 'hospital',
  '병리과': 'hospital',
  '방사선종양학과': 'hospital',
  '핵의학과': 'hospital',
  '가정의학과': 'hospital',
  '응급의학과': 'hospital',
  '직업환경의학과': 'hospital',
  '예방의학과': 'hospital',
  '소아청소년과': 'hospital',
  '삼성서울병원': 'hospital',
  '서울아산병원': 'hospital',
  '세브란스': 'hospital',
  '서울대병원': 'hospital',
  '고려대병원': 'hospital',
  '성모병원': 'hospital',
  '중앙대병원': 'hospital',

  // ── 약국 ──
  '약국': 'pharmacy',
  '드럭스토어': 'pharmacy',
  '온누리약국': 'pharmacy',
  '대학약국': 'pharmacy',
  '보건소': 'pharmacy',
  '조제약': 'pharmacy',
  '처방전': 'pharmacy',
  '동네약국': 'pharmacy',

  // ── 동물병원 ──
  '동물병원': 'medical',
  '수의사': 'medical',
  '애견병원': 'medical',
  '동물의료센터': 'medical',
  '펫클리닉': 'medical',

  // ── 학원 / 교육 ──
  '학원': 'academy',
  '어학원': 'academy',
  '영어학원': 'academy',
  '수학학원': 'academy',
  '입시학원': 'academy',
  '태권도': 'academy',
  '피아노': 'academy',
  '음악학원': 'academy',
  '미술학원': 'academy',
  '운전면허': 'academy',
  '자동차학원': 'academy',
  '수영': 'academy',
  '체육관': 'academy',
  '발레': 'academy',
  '무용': 'academy',
  '코딩학원': 'academy',
  '로봇학원': 'academy',
  '과학학원': 'academy',
  '논술학원': 'academy',
  '독서실': 'academy',
  '스터디카페': 'academy',
  '공유오피스': 'academy',
  '위워크': 'academy',
  '패스트파이브': 'academy',
  '토익학원': 'academy',
  '토플학원': 'academy',
  'YBM': 'academy',
  '해커스': 'academy',
  '시원스쿨': 'academy',
  '야나두': 'academy',
  '스피킹맥스': 'academy',
  '교습소': 'academy',
  '유치원': 'academy',
  '어린이집': 'academy',
  '보습학원': 'academy',
  '피아노학원': 'academy',
  '바둑학원': 'academy',
  '서예학원': 'academy',
  '합기도': 'academy',
  '유도': 'academy',
  '검도': 'academy',
  '축구교실': 'academy',
  '야구교실': 'academy',
  '농구교실': 'academy',
  '수영교실': 'academy',
  '체조교실': 'academy',
  '발레학원': 'academy',
  '댄스학원': 'academy',
  '방송댄스': 'academy',
  '보컬학원': 'academy',
  '기타학원': 'academy',
  '드럼학원': 'academy',
  '바이올린학원': 'academy',
  '플루트학원': 'academy',
  '중국어학원': 'academy',
  '일본어학원': 'academy',
  '스페인어학원': 'academy',
  '프랑스어학원': 'academy',
  '국어학원': 'academy',

  // ── 온라인 교육 ──
  '클래스101': 'education',
  '패스트캠퍼스': 'education',
  '인프런': 'education',
  '에듀윌': 'education',
  '메가스터디': 'education',
  '이투스': 'education',
  '대성마이맥': 'education',
  '유데미': 'education',
  'udemy': 'education',
  '코세라': 'education',
  'coursera': 'education',
  '탈잉': 'education',
  '크몽': 'education',
  '숨고': 'education',
  '프로그래머스': 'education',
  '코드잇': 'education',
  '엘리스': 'education',
  '노마드코더': 'education',
  '생활코딩': 'education',
  '구름': 'education',
  '제로베이스': 'education',
  '위코드': 'education',
  '듀오링고': 'education',
  'duolingo': 'education',

  // ── 도서 ──
  '교보문고': 'books',
  'kyobo': 'books',
  '알라딘': 'books',
  '예스24': 'books',
  'yes24': 'books',
  '영풍문고': 'books',
  '반디앤루니스': 'books',
  '북스리브로': 'books',
  '밀리의서재온라인': 'books',
  '리디셀렉트': 'books',
  '인터넷서점': 'books',
  '서점': 'books',
  '도서': 'books',
  '북센': 'books',
  '중고서점': 'books',
  '알라딘중고서점': 'books',
  '교보핫트랙스도서': 'books',

  // ── 항공 ──
  '대한항공': 'airline',
  'korean air': 'airline',
  '아시아나': 'airline',
  'asiana': 'airline',
  '제주항공': 'airline',
  'jeju air': 'airline',
  '진에어': 'airline',
  'jin air': 'airline',
  '티웨이항공': 'airline',
  't\'way': 'airline',
  '에어서울': 'airline',
  '에어부산': 'airline',
  '에어프레미아': 'airline',
  '이스타항공': 'airline',
  '플라이강원': 'airline',
  '하이에어': 'airline',
  '비엣젯': 'airline',
  'vietjet': 'airline',
  '피치항공': 'airline',
  'peach': 'airline',
  '중국동방항공': 'airline',
  '중국남방항공': 'airline',
  '일본항공': 'airline',
  'jal': 'airline',
  '전일본공수': 'airline',
  'ana': 'airline',
  '싱가포르항공': 'airline',
  'singapore airlines': 'airline',
  '카타르항공': 'airline',
  'qatar airways': 'airline',
  '에미레이트': 'airline',
  'emirates': 'airline',
  '터키항공': 'airline',
  'turkish airlines': 'airline',
  '루프트한자': 'airline',
  'lufthansa': 'airline',
  '에어프랑스': 'airline',
  'air france': 'airline',
  '영국항공': 'airline',
  'british airways': 'airline',
  '델타항공': 'airline',
  'delta': 'airline',
  '유나이티드항공': 'airline',
  'united airlines': 'airline',
  '아메리칸항공': 'airline',
  'american airlines': 'airline',
  '캐세이퍼시픽': 'airline',
  'cathay pacific': 'airline',
  '타이항공': 'airline',
  'thai airways': 'airline',
  '에어아시아': 'airline',
  'airasia': 'airline',
  '스쿠트': 'airline',
  'scoot': 'airline',
  '항공권': 'airline',
  '스카이스캐너항공': 'airline',

  // ── 숙박 ──
  '야놀자': 'hotel',
  '여기어때': 'hotel',
  'airbnb': 'hotel',
  '에어비앤비': 'hotel',
  '호텔스닷컴': 'hotel',
  'hotels.com': 'hotel',
  '부킹닷컴': 'hotel',
  'booking.com': 'hotel',
  '아고다': 'hotel',
  'agoda': 'hotel',
  '힐튼': 'hotel',
  '메리어트': 'hotel',
  '인터컨티넨탈': 'hotel',
  '롯데호텔': 'hotel',
  '신라호텔': 'hotel',
  '조선호텔': 'hotel',
  '워커힐': 'hotel',
  '그랜드하얏트': 'hotel',
  'JW메리어트': 'hotel',
  '파크하얏트': 'hotel',
  '포시즌스': 'hotel',
  '콘래드': 'hotel',
  '웨스틴': 'hotel',
  '쉐라톤': 'hotel',
  '이비스': 'hotel',
  '노보텔': 'hotel',
  '켄싱턴': 'hotel',
  '한화리조트': 'hotel',
  '대명리조트': 'hotel',
  '소노호텔': 'hotel',
  '페어몬트': 'hotel',
  '앰배서더': 'hotel',
  '라마다': 'hotel',
  '홀리데이인': 'hotel',
  '베스트웨스턴': 'hotel',
  '코트야드': 'hotel',
  '르메르디앙': 'hotel',
  '반얀트리': 'hotel',
  '나인트리': 'hotel',
  '글래드': 'hotel',
  '오크우드': 'hotel',
  '서머셋': 'hotel',
  '프레이저': 'hotel',
  '호텔': 'hotel',
  '모텔': 'hotel',
  '게스트하우스': 'hotel',
  '민박': 'hotel',
  '리조트': 'hotel',
  '콘도': 'hotel',
  '풀빌라': 'hotel',
  '한옥스테이': 'hotel',
  '호스텔': 'hotel',

  // ── 여행 ──
  '하나투어': 'travel',
  '모두투어': 'travel',
  '노랑풍선': 'travel',
  '참좋은여행': 'travel',
  '클룩': 'travel',
  'klook': 'travel',
  '트립닷컴': 'travel',
  'trip.com': 'travel',
  '스카이스캐너': 'travel',
  '여행박사': 'travel',
  '트리플': 'travel',
  '마이리얼트립': 'travel',
  '타비': 'travel',
  '익스피디아': 'travel',
  'expedia': 'travel',
  '카약': 'travel',
  'kayak': 'travel',
  '인터파크투어': 'travel',
  '와그': 'travel',
  '투어비스': 'travel',
  '투어팁스': 'travel',
  '한진관광': 'travel',
  '롯데관광': 'travel',
  '온라인투어': 'travel',
  '웹투어': 'travel',
  '자유투어': 'travel',
  '호핑투어': 'travel',
  '여행사': 'travel',
  '패키지여행': 'travel',

  // ── 공과금 / 관리비 ──
  '한국전력': 'utilities',
  '한전': 'utilities',
  '도시가스': 'utilities',
  '수도요금': 'utilities',
  '관리비': 'utilities',
  '아파트관리비': 'utilities',
  '국민건강보험': 'utilities',
  '국민연금': 'utilities',
  '서울시수도': 'utilities',
  '인천수도': 'utilities',
  '한국가스공사': 'utilities',
  '지역난방': 'utilities',
  '아파트월세': 'utilities',
  '전세대출이자': 'utilities',
  '관리사무소': 'utilities',
  '전기요금': 'utilities',
  '전기세': 'utilities',
  '가스요금': 'utilities',
  '가스비': 'utilities',
  '수도세': 'utilities',
  '상수도': 'utilities',
  '하수도': 'utilities',
  '공과금': 'utilities',
  '공동관리비': 'utilities',
  '난방비': 'utilities',
  '지방세': 'utilities',
  '재산세': 'utilities',
  '자동차세': 'utilities',
  '종합소득세': 'utilities',
  '주민세': 'utilities',

  // ── 렌터카 / 차량 ──
  '쏘카': 'transportation',
  'socar': 'transportation',
  '그린카': 'transportation',
  '카카오T렌터카': 'transportation',
  '롯데렌터카': 'transportation',
  'sk렌터카': 'transportation',
  '현대렌터카': 'transportation',
  '제주렌터카': 'transportation',
  'AJ렌터카': 'transportation',
  '카렌트': 'transportation',
  '자동차정비': 'transportation',
  '카센터': 'transportation',
  '타이어뱅크': 'transportation',
  '오토오아시스': 'transportation',
  '세차장': 'transportation',
  '오토글래스': 'transportation',
  '자동차검사': 'transportation',
  '엔카': 'transportation',
  'kcar': 'transportation',
  '케이카': 'transportation',
  '헤이딜러': 'transportation',
  '첫차': 'transportation',
  '중고차': 'transportation',
  '카닥': 'transportation',
  '타이어프로': 'transportation',
  '금호타이어': 'transportation',
  '한국타이어': 'transportation',
  '넥센타이어': 'transportation',
  '자동차보험수리': 'transportation',
  '판금도색': 'transportation',
  '블루핸즈': 'transportation',
  '오토큐': 'transportation',
  '스피드메이트': 'transportation',
  '폴스타': 'transportation',

  // ── 반려동물 ──
  '펫샵': 'offline_shopping',
  '애견용품': 'offline_shopping',
  '고양이용품': 'offline_shopping',
  '펫푸드': 'offline_shopping',
  '사료': 'offline_shopping',

  // ── 기타 ──

  // ════════════════════════════════════════════════════════════════════
  // ── EXPANDED ENTRIES: English/romanized names for Korean merchants ─
  // ════════════════════════════════════════════════════════════════════

  // ── 카페 / 커피 (영문) ──
  'ediya': 'dining.cafe',
  'paikdabang': 'dining.cafe',
  'paik\'s coffee': 'dining.cafe',
  'mega coffee': 'dining.cafe',
  'mega mgc': 'dining.cafe',
  'compose coffee': 'dining.cafe',
  'hollys': 'dining.cafe',
  'hollys coffee': 'dining.cafe',
  'paul bassett': 'dining.cafe',
  'pascucci': 'dining.cafe',
  'the venti': 'dining.cafe',
  'caffe bene': 'dining.cafe',
  'caffebene': 'dining.cafe',
  'tom n toms': 'dining.cafe',
  'tomntoms': 'dining.cafe',
  'angel-in-us': 'dining.cafe',
  'angelinus': 'dining.cafe',
  'blue bottle': 'dining.cafe',
  'bluebottle': 'dining.cafe',
  'coffeesmith': 'dining.cafe',
  'mammoth coffee': 'dining.cafe',
  'gong cha': 'dining.cafe',
  'gongcha': 'dining.cafe',
  'juicy': 'dining.cafe',
  'auntie anne': 'dining.cafe',
  'dalkom coffee': 'dining.cafe',
  'droptop': 'dining.cafe',
  'coffine gurunaru': 'dining.cafe',
  'beans bins': 'dining.cafe',
  'beansbins': 'dining.cafe',
  'bonavi': 'dining.cafe',
  'twosome place': 'dining.cafe',
  'a twosome place': 'dining.cafe',
  'topresso': 'dining.cafe',
  'selecto coffee': 'dining.cafe',
  'the cafe': 'dining.cafe',
  'caffe tiamo': 'dining.cafe',
  'jo\'s coffee': 'dining.cafe',
  'dessert39': 'dining.cafe',
  'dessert 39': 'dining.cafe',
  'waffle university': 'dining.cafe',
  'yogerpresso': 'dining.cafe',
  'milk hall': 'dining.cafe',
  'cafe de paris': 'dining.cafe',
  'banapresso': 'dining.cafe',
  'the liter': 'dining.cafe',
  'bean brothers': 'dining.cafe',
  'fritz': 'dining.cafe',
  'center coffee': 'dining.cafe',
  'onion': 'dining.cafe',
  'terarosa': 'dining.cafe',
  'momos coffee': 'dining.cafe',
  'namusairo': 'dining.cafe',
  'luft coffee': 'dining.cafe',
  'felt coffee': 'dining.cafe',
  'coffee libre': 'dining.cafe',
  'smoothie king': 'dining.cafe',
  'tiger sugar': 'dining.cafe',
  'palgong tea': 'dining.cafe',
  'osulloc': 'dining.cafe',
  'o\'sulloc': 'dining.cafe',
  'gamsungcoffee': 'dining.cafe',
  'manlab coffee': 'dining.cafe',
  'hasam coffee': 'dining.cafe',

  // ── 베이커리 / 디저트 (영문) ──
  'paris baguette': 'dining.cafe',
  'parisbaguette': 'dining.cafe',
  'paris croissant': 'dining.cafe',
  'tous les jours': 'dining.cafe',
  'tlj': 'dining.cafe',
  'dunkin': 'dining.cafe',
  'dunkin donuts': 'dining.cafe',
  'krispy kreme': 'dining.cafe',
  'krispykreme': 'dining.cafe',
  'baskin robbins': 'dining.cafe',
  'baskinrobbins': 'dining.cafe',
  'baskin-robbins': 'dining.cafe',
  'sulbing': 'dining.cafe',
  'sungsimdang': 'dining.cafe',
  'natuur': 'dining.cafe',
  'hong lui zen': 'dining.cafe',
  'breadenco': 'dining.cafe',
  'pain de papa': 'dining.cafe',
  'montchoix': 'dining.cafe',
  'our bakery': 'dining.cafe',
  'mildo': 'dining.cafe',
  'knotted': 'dining.cafe',
  'london bagel museum': 'dining.cafe',
  'haagen-dazs': 'dining.cafe',
  'haagendazs': 'dining.cafe',
  'cold stone': 'dining.cafe',
  'coldstone': 'dining.cafe',
  'gelato': 'dining.cafe',

  // ── 패스트푸드 (영문) ──
  'mcdonalds': 'dining.fast_food',
  'mcdonald\'s': 'dining.fast_food',
  'burgerking': 'dining.fast_food',
  'lotteria': 'dining.fast_food',
  'mom\'s touch': 'dining.fast_food',
  'momstouch': 'dining.fast_food',
  'moms touch': 'dining.fast_food',
  'popeyes': 'dining.fast_food',
  'no brand burger': 'dining.fast_food',
  'shake shack': 'dining.fast_food',
  'shakeshack': 'dining.fast_food',
  'five guys': 'dining.fast_food',
  'fiveguys': 'dining.fast_food',
  'isaac toast': 'dining.fast_food',
  'chipotle': 'dining.fast_food',
  'taco bell': 'dining.fast_food',
  'tacobell': 'dining.fast_food',
  'wendy\'s': 'dining.fast_food',
  'wendys': 'dining.fast_food',
  'chick-fil-a': 'dining.fast_food',
  'chickfila': 'dining.fast_food',
  'panda express': 'dining.fast_food',
  'pandaexpress': 'dining.fast_food',
  'in-n-out': 'dining.fast_food',
  'innout': 'dining.fast_food',
  'whataburger': 'dining.fast_food',
  'jack in the box': 'dining.fast_food',
  'sonic drive': 'dining.fast_food',
  'arby\'s': 'dining.fast_food',
  'arbys': 'dining.fast_food',
  'carl\'s jr': 'dining.fast_food',
  'hardee\'s': 'dining.fast_food',
  'white castle': 'dining.fast_food',
  'wingstop': 'dining.fast_food',
  'el pollo loco': 'dining.fast_food',
  'culver\'s': 'dining.fast_food',
  'raising cane': 'dining.fast_food',
  'jollibee': 'dining.fast_food',
  'frankburger': 'dining.fast_food',
  'downtowner': 'dining.fast_food',
  'cry cheese burger': 'dining.fast_food',
  'shinjeon': 'dining.fast_food',
  'sindangdong tteokbokki': 'dining.fast_food',

  // ── 치킨 / 피자 (영문) ──
  'kyochon': 'dining.delivery',
  'kyochon chicken': 'dining.delivery',
  'bbq chicken': 'dining.delivery',
  'bbq': 'dining.delivery',
  'nene chicken': 'dining.delivery',
  'nenechicken': 'dining.delivery',
  'goobne': 'dining.delivery',
  'goobne chicken': 'dining.delivery',
  'bhc chicken': 'dining.delivery',
  'ttoraeore': 'dining.delivery',
  'hosigi': 'dining.delivery',
  'cheogajip': 'dining.delivery',
  'puradak': 'dining.delivery',
  'puradak chicken': 'dining.delivery',
  'dominos': 'dining.delivery',
  'domino\'s': 'dining.delivery',
  'mr. pizza': 'dining.delivery',
  'mr pizza': 'dining.delivery',
  'papa john\'s': 'dining.delivery',
  'papa johns': 'dining.delivery',
  'papajohns': 'dining.delivery',
  '60gye chicken': 'dining.delivery',
  'jadam chicken': 'dining.delivery',
  'pelicana': 'dining.delivery',
  'jicobba chicken': 'dining.delivery',
  'barun chicken': 'dining.delivery',
  'norang tongdak': 'dining.delivery',
  'mexicana chicken': 'dining.delivery',
  'chicken mania': 'dining.delivery',
  'pizza maru': 'dining.delivery',
  'gopizza': 'dining.delivery',
  'pizza school': 'dining.delivery',
  'pizza alvolo': 'dining.delivery',

  // ── 음식 배달 (영문) ──
  'baemin': 'dining.delivery',
  'baedal minjok': 'dining.delivery',
  'yogiyo': 'dining.delivery',
  'coupang eats': 'dining.delivery',
  'uber eats': 'dining.delivery',
  'ubereats': 'dining.delivery',
  'doordash': 'dining.delivery',
  'grubhub': 'dining.delivery',
  'postmates': 'dining.delivery',
  'deliveroo': 'dining.delivery',
  'foodpanda': 'dining.delivery',
  'grab food': 'dining.delivery',
  'grabfood': 'dining.delivery',
  'just eat': 'dining.delivery',

  // ── 외식 체인 / 일반 음식점 (영문) ──
  'outback steakhouse': 'dining.restaurant',
  'ashley': 'dining.restaurant',
  'mad for garlic': 'dining.restaurant',
  'hansot': 'dining.restaurant',
  'bonjuk': 'dining.restaurant',
  'bon juk': 'dining.restaurant',
  'gimbap cheonguk': 'dining.restaurant',
  'kimbap cheonguk': 'dining.restaurant',
  'kimganae': 'dining.restaurant',
  'nolbu': 'dining.restaurant',
  'theborn korea': 'dining.restaurant',
  'saemaeul': 'dining.restaurant',
  'saemaeul sikdang': 'dining.restaurant',
  'baeknyeonok': 'dining.restaurant',
  'hanbul': 'dining.restaurant',
  'wonhalmeoni': 'dining.restaurant',
  'hansinpocha': 'dining.restaurant',
  'ichadol': 'dining.restaurant',
  'hanam pig': 'dining.restaurant',
  'myeongryun': 'dining.restaurant',
  'myeongrunjinsa': 'dining.restaurant',
  'hongkong banjum': 'dining.restaurant',
  'yeokjeon udon': 'dining.restaurant',
  'misoya': 'dining.restaurant',
  'hakoya': 'dining.restaurant',
  'sushiro': 'dining.restaurant',
  'kurasushi': 'dining.restaurant',
  'kura sushi': 'dining.restaurant',
  'katsuya': 'dining.restaurant',
  'jungdon': 'dining.restaurant',
  'saboten': 'dining.restaurant',
  'gyukatsu': 'dining.restaurant',
  'the place': 'dining.restaurant',
  'todai': 'dining.restaurant',
  'season\'s table': 'dining.restaurant',
  'olban': 'dining.restaurant',
  'jayeonbyeolgok': 'dining.restaurant',
  'pulipchae': 'dining.restaurant',
  'bongchu': 'dining.restaurant',
  'yugane': 'dining.restaurant',
  'chaesundang': 'dining.restaurant',
  'panera': 'dining.restaurant',
  'panera bread': 'dining.restaurant',
  'olive garden': 'dining.restaurant',
  'applebee': 'dining.restaurant',
  'applebees': 'dining.restaurant',
  'denny\'s': 'dining.restaurant',
  'dennys': 'dining.restaurant',
  'ihop': 'dining.restaurant',
  'red lobster': 'dining.restaurant',
  'cheesecake factory': 'dining.restaurant',
  'p.f. chang': 'dining.restaurant',
  'pf changs': 'dining.restaurant',
  'cracker barrel': 'dining.restaurant',
  'waffle house': 'dining.restaurant',
  'chili\'s': 'dining.restaurant',
  'chilis': 'dining.restaurant',
  'buffalo wild wings': 'dining.restaurant',
  'texas roadhouse': 'dining.restaurant',
  'longhorn steakhouse': 'dining.restaurant',
  'tgi friday': 'dining.restaurant',
  'tgif': 'dining.restaurant',
  'bonefish grill': 'dining.restaurant',
  'ruth\'s chris': 'dining.restaurant',
  'ruthschris': 'dining.restaurant',
  'nobu': 'dining.restaurant',
  'benihana': 'dining.restaurant',
  'morton\'s': 'dining.restaurant',

  // ── 대형마트 / 식료품 (영문) ──
  'e-mart': 'grocery.supermarket',
  'emart everyday': 'grocery.supermarket',
  'homeplus express': 'grocery.supermarket',
  'lotte mart': 'grocery.supermarket',
  'lottemart': 'grocery.supermarket',
  'lotte super': 'grocery.supermarket',
  'nonghyup hanaro': 'grocery.supermarket',
  'hanaro club': 'grocery.supermarket',
  'no brand': 'grocery.supermarket',
  'nobrand': 'grocery.supermarket',
  'traders': 'grocery.supermarket',
  'mega mart': 'grocery.supermarket',
  'gs the fresh': 'grocery.supermarket',
  'shinsegae food': 'grocery.supermarket',
  'kim\'s club': 'grocery.supermarket',
  'walmart': 'grocery.supermarket',
  'whole foods': 'grocery.supermarket',
  'wholefoods': 'grocery.supermarket',
  'trader joe': 'grocery.supermarket',
  'trader joes': 'grocery.supermarket',
  'trader joe\'s': 'grocery.supermarket',
  'kroger': 'grocery.supermarket',
  'safeway': 'grocery.supermarket',
  'albertsons': 'grocery.supermarket',
  'publix': 'grocery.supermarket',
  'aldi': 'grocery.supermarket',
  'lidl': 'grocery.supermarket',
  'h mart': 'grocery.supermarket',
  'hmart': 'grocery.supermarket',
  'costco wholesale': 'grocery.supermarket',
  'sam\'s club': 'grocery.supermarket',
  'sams club': 'grocery.supermarket',
  'bj\'s wholesale': 'grocery.supermarket',
  'wegmans': 'grocery.supermarket',
  'meijer': 'grocery.supermarket',
  'winco': 'grocery.supermarket',
  'piggly wiggly': 'grocery.supermarket',
  'food lion': 'grocery.supermarket',
  'giant eagle': 'grocery.supermarket',
  'stop and shop': 'grocery.supermarket',
  'sprouts': 'grocery.supermarket',
  'fresh market': 'grocery.supermarket',
  'market basket': 'grocery.supermarket',
  'tesco': 'grocery.supermarket',
  'sainsbury': 'grocery.supermarket',
  'carrefour': 'grocery.supermarket',
  'woolworths': 'grocery.supermarket',

  // ── 온라인 장보기 (영문) ──
  'market kurly': 'grocery.online_grocery',
  'kurly': 'grocery.online_grocery',
  'oasis market': 'grocery.online_grocery',
  'b mart': 'grocery.online_grocery',
  'coupang rocket fresh': 'grocery.online_grocery',
  'hello nature': 'grocery.online_grocery',
  'rocket fresh': 'grocery.online_grocery',
  'ssg.com': 'grocery.online_grocery',
  'emart mall': 'grocery.online_grocery',
  'instacart': 'grocery.online_grocery',
  'freshdirect': 'grocery.online_grocery',
  'peapod': 'grocery.online_grocery',
  'thrive market': 'grocery.online_grocery',
  'amazon fresh': 'grocery.online_grocery',

  // ── 편의점 (영문/법인명) ──
  'seven eleven': 'convenience_store',
  'ministop': 'convenience_store',
  'emart24': 'convenience_store',
  'e-mart 24': 'convenience_store',
  'storyway': 'convenience_store',
  'withme': 'convenience_store',
  '비지에프리테일': 'convenience_store',
  'bgf리테일': 'convenience_store',
  'bgf retail': 'convenience_store',
  '지에스리테일': 'convenience_store',
  'gs리테일': 'convenience_store',
  'gs retail': 'convenience_store',
  '코리아세븐': 'convenience_store',
  'korea seven': 'convenience_store',

  // ── 온라인 쇼핑 (추가) ──
  'naver shopping': 'online_shopping',
  'naver pay': 'online_shopping',
  'naverpay': 'online_shopping',
  '11st': 'online_shopping',
  'wemakeprice': 'online_shopping',
  'tmon': 'online_shopping',
  'ticketmonster': 'online_shopping',
  'interpark': 'online_shopping',
  'kakao shopping': 'online_shopping',
  'daangn': 'online_shopping',
  'danggeun': 'online_shopping',
  'karrot': 'online_shopping',
  'bunjang': 'online_shopping',
  'idus': 'online_shopping',
  'ohouse': 'online_shopping',
  'today\'s house': 'online_shopping',
  'coupang rocket': 'online_shopping',
  'naver smartstore': 'online_shopping',
  'kakao gift': 'online_shopping',
  'lotte on': 'online_shopping',
  'lotteimall': 'online_shopping',
  'himart online': 'online_shopping',
  'payco': 'online_shopping',
  'samsung pay': 'online_shopping',
  'apple pay': 'online_shopping',
  'catch fashion': 'online_shopping',
  'balaan': 'online_shopping',
  'trenbe': 'online_shopping',
  'mustit': 'online_shopping',
  'etsy': 'online_shopping',
  'wayfair': 'online_shopping',
  'overstock': 'online_shopping',
  'rakuten': 'online_shopping',
  'wish': 'online_shopping',
  'mercari': 'online_shopping',
  'poshmark': 'online_shopping',
  'depop': 'online_shopping',
  'stockx': 'online_shopping',
  'goat': 'online_shopping',
  'farfetch': 'online_shopping',
  'net-a-porter': 'online_shopping',
  'mytheresa': 'online_shopping',
  'ssense': 'online_shopping',
  'shopify': 'online_shopping',
  'target': 'online_shopping',
  'target.com': 'online_shopping',
  'best buy': 'online_shopping',
  'bestbuy': 'online_shopping',
  'newegg': 'online_shopping',
  'b&h photo': 'online_shopping',
  'zappos': 'online_shopping',
  'nordstrom': 'online_shopping',
  'macys': 'online_shopping',
  'macy\'s': 'online_shopping',
  'bloomingdales': 'online_shopping',
  'saks fifth avenue': 'online_shopping',
  'asos': 'online_shopping',
  'boohoo': 'online_shopping',
  'jd.com': 'online_shopping',
  'pinduoduo': 'online_shopping',
  'lazada': 'online_shopping',
  'shopee': 'online_shopping',
  'tokopedia': 'online_shopping',
  'flipkart': 'online_shopping',

  // ── 패션 / 의류 (영문 추가) ──
  'ably': 'fashion',
  'zigzag': 'fashion',
  'brandi': 'fashion',
  'w concept': 'fashion',
  'handsome': 'fashion',
  'the handsome': 'fashion',
  'new balance': 'fashion',
  'newbalance': 'fashion',
  'abc mart': 'fashion',
  'abcmart': 'fashion',
  'topten': 'fashion',
  'top ten': 'fashion',
  'spao': 'fashion',
  'eight seconds': 'fashion',
  'polo ralph lauren': 'fashion',
  'ralph lauren': 'fashion',
  'kangol': 'fashion',
  'discovery': 'fashion',
  'discovery expedition': 'fashion',
  'north face': 'fashion',
  'northface': 'fashion',
  'black yak': 'fashion',
  'blackyak': 'fashion',
  'kolon sport': 'fashion',
  'kolonsport': 'fashion',
  'eider': 'fashion',
  'giordano': 'fashion',
  'massimo dutti': 'fashion',
  'massimodutti': 'fashion',
  'cos': 'fashion',
  'and other stories': 'fashion',
  'lacoste': 'fashion',
  'tommy hilfiger': 'fashion',
  'calvin klein': 'fashion',
  'calvinklein': 'fashion',
  'guess': 'fashion',
  'levis': 'fashion',
  'levi\'s': 'fashion',
  'reebok': 'fashion',
  'dr. martens': 'fashion',
  'dr martens': 'fashion',
  'ecco': 'fashion',
  'clarks': 'fashion',
  'mizuno': 'fashion',
  'asics': 'fashion',
  'hoka': 'fashion',
  'on running': 'fashion',
  'onrunning': 'fashion',
  'salomon': 'fashion',
  'shumarker': 'fashion',
  'footlocker': 'fashion',
  'foot locker': 'fashion',
  'lesmore': 'fashion',
  'old navy': 'fashion',
  'forever 21': 'fashion',
  'forever21': 'fashion',
  'primark': 'fashion',
  'lv': 'fashion',
  'hermès': 'fashion',
  'valentino': 'fashion',
  'bottega veneta': 'fashion',
  'bottegaveneta': 'fashion',
  'loewe': 'fashion',
  'moncler': 'fashion',
  'fendi': 'fashion',
  'givenchy': 'fashion',
  'saint laurent': 'fashion',
  'ysl': 'fashion',
  'celine': 'fashion',
  'tiffany': 'fashion',
  'tiffany & co': 'fashion',
  'cartier': 'fashion',
  'rolex': 'fashion',
  'omega': 'fashion',
  'tag heuer': 'fashion',
  'iwc': 'fashion',
  'versace': 'fashion',
  'dolce gabbana': 'fashion',
  'dolce & gabbana': 'fashion',
  'armani': 'fashion',
  'giorgio armani': 'fashion',
  'emporio armani': 'fashion',
  'hugo boss': 'fashion',
  'michael kors': 'fashion',
  'coach': 'fashion',
  'kate spade': 'fashion',
  'marc jacobs': 'fashion',
  'off-white': 'fashion',
  'stone island': 'fashion',
  'acne studios': 'fashion',
  'maison margiela': 'fashion',
  'alexander mcqueen': 'fashion',
  'tom ford': 'fashion',
  'balmain': 'fashion',
  'thom browne': 'fashion',
  'ami paris': 'fashion',
  'kenzo': 'fashion',
  'isabel marant': 'fashion',
  'miu miu': 'fashion',
  'jimmy choo': 'fashion',
  'manolo blahnik': 'fashion',
  'christian louboutin': 'fashion',
  'salvatore ferragamo': 'fashion',
  'tod\'s': 'fashion',
  'bvlgari': 'fashion',
  'bulgari': 'fashion',
  'van cleef': 'fashion',
  'van cleef & arpels': 'fashion',
  'pandora': 'fashion',
  'swarovski': 'fashion',
  'brooks brothers': 'fashion',
  'banana republic': 'fashion',
  'j.crew': 'fashion',
  'jcrew': 'fashion',
  'anthropologie': 'fashion',
  'free people': 'fashion',
  'urban outfitters': 'fashion',
  'lululemon': 'fashion',
  'under armour': 'fashion',
  'underarmour': 'fashion',
  'columbia sportswear': 'fashion',
  'arcteryx': 'fashion',
  'arc\'teryx': 'fashion',
  'mammut': 'fashion',
  'fjallraven': 'fashion',

  // ── 백화점 (영문) ──
  'lotte department': 'department_store',
  'lotte dept': 'department_store',
  'hyundai department': 'department_store',
  'shinsegae dept': 'department_store',
  'galleria': 'department_store',
  'the hyundai': 'department_store',
  'the hyundai seoul': 'department_store',
  'starfield': 'department_store',
  'starfield hanam': 'department_store',
  'starfield goyang': 'department_store',
  'ak plaza': 'department_store',
  'nc department': 'department_store',
  'lotte outlet': 'department_store',
  'lotte premium outlet': 'department_store',
  'hyundai premium outlet': 'department_store',
  'shinsegae outlet': 'department_store',

  // ── 뷰티 / 화장품 (영문) ──
  'olive young': 'offline_shopping',
  'oliveyoung': 'offline_shopping',
  'chicor': 'offline_shopping',
  'lohbs': 'offline_shopping',
  'innisfree': 'offline_shopping',
  'amorepacific': 'offline_shopping',
  'amore pacific': 'offline_shopping',
  'etude': 'offline_shopping',
  'etude house': 'offline_shopping',
  'missha': 'offline_shopping',
  'the face shop': 'offline_shopping',
  'thefaceshop': 'offline_shopping',
  'nature republic': 'offline_shopping',
  'naturerepublic': 'offline_shopping',
  'skin food': 'offline_shopping',
  'skinfood': 'offline_shopping',
  'tonymoly': 'offline_shopping',
  'tony moly': 'offline_shopping',
  'clio': 'offline_shopping',
  'laneige': 'offline_shopping',
  'sulwhasoo': 'offline_shopping',
  'hera': 'offline_shopping',
  'mac cosmetics': 'offline_shopping',
  'estee lauder': 'offline_shopping',
  'esteelauder': 'offline_shopping',
  'lancome': 'offline_shopping',
  'lancôme': 'offline_shopping',
  'bobbi brown': 'offline_shopping',
  'bobibrown': 'offline_shopping',
  'nars': 'offline_shopping',
  'clinique': 'offline_shopping',
  'shiseido': 'offline_shopping',
  'sk-ii': 'offline_shopping',
  'skii': 'offline_shopping',
  'ulta': 'offline_shopping',
  'ulta beauty': 'offline_shopping',
  'bath body works': 'offline_shopping',
  'bath & body works': 'offline_shopping',
  'l\'occitane': 'offline_shopping',
  'loccitane': 'offline_shopping',
  'kiehls': 'offline_shopping',
  'kiehl\'s': 'offline_shopping',
  'origins': 'offline_shopping',
  'benefit cosmetics': 'offline_shopping',
  'too faced': 'offline_shopping',
  'urban decay': 'offline_shopping',
  'charlotte tilbury': 'offline_shopping',
  'fenty beauty': 'offline_shopping',
  'rare beauty': 'offline_shopping',
  'glossier': 'offline_shopping',
  'it cosmetics': 'offline_shopping',
  'dr jart': 'offline_shopping',
  'dr.jart': 'offline_shopping',
  'cosrx': 'offline_shopping',
  'banila co': 'offline_shopping',
  'rom&nd': 'offline_shopping',
  'romand': 'offline_shopping',
  'peripera': 'offline_shopping',
  'holika holika': 'offline_shopping',
  'mamonde': 'offline_shopping',
  'iope': 'offline_shopping',
  'primera': 'offline_shopping',
  'hanyul': 'offline_shopping',
  'vt cosmetics': 'offline_shopping',

  // ── 오프라인 쇼핑 / 리테일 (영문/추가) ──
  'office depot': 'offline_shopping',
  'morning glory': 'offline_shopping',
  'hottracks': 'offline_shopping',
  'artbox': 'offline_shopping',
  'livingbox': 'offline_shopping',
  'hanssem': 'offline_shopping',
  'hanssem design park': 'offline_shopping',
  'casamia': 'offline_shopping',
  'iloom': 'offline_shopping',
  'simmons': 'offline_shopping',
  'ace bed': 'offline_shopping',
  'acebed': 'offline_shopping',
  'pet friends': 'offline_shopping',
  'petfriends': 'offline_shopping',
  'biteme': 'offline_shopping',
  'creanetopia': 'offline_shopping',
  'cleannetopia': 'offline_shopping',
  'laundrygo': 'offline_shopping',
  'ikea korea': 'offline_shopping',
  'samsung electronics': 'offline_shopping',
  'hi mart': 'offline_shopping',
  'himart': 'offline_shopping',
  'electronic land': 'offline_shopping',
  'cuckoo': 'offline_shopping',
  'lg electronics': 'offline_shopping',
  'apple store': 'offline_shopping',
  'apple korea': 'offline_shopping',
  'coway': 'offline_shopping',
  'dyson korea': 'offline_shopping',
  'philips': 'offline_shopping',
  'coin wash': 'offline_shopping',
  'flower market': 'offline_shopping',
  'lens me': 'offline_shopping',
  'lensme': 'offline_shopping',
  'microsoft store': 'offline_shopping',
  'pier 1': 'offline_shopping',
  'pottery barn': 'offline_shopping',
  'crate barrel': 'offline_shopping',
  'crate & barrel': 'offline_shopping',
  'williams sonoma': 'offline_shopping',
  'restoration hardware': 'offline_shopping',
  'bed bath beyond': 'offline_shopping',
  'container store': 'offline_shopping',
  'home depot': 'offline_shopping',
  'lowe\'s': 'offline_shopping',
  'lowes': 'offline_shopping',
  'costco optical': 'offline_shopping',
  'pearle vision': 'offline_shopping',
  'lenscrafters': 'offline_shopping',
  'petco': 'offline_shopping',
  'petsmart': 'offline_shopping',
  'chewy': 'offline_shopping',
  'michaels': 'offline_shopping',
  'hobby lobby': 'offline_shopping',
  'joann': 'offline_shopping',

  // ── 택시 (영문) ──
  'kakao taxi': 'taxi',
  'kakaot': 'taxi',
  'kakao t': 'taxi',
  'kakao mobility': 'taxi',
  'tada': 'taxi',
  'uber': 'taxi',
  'lyft': 'taxi',
  'grab': 'taxi',
  'grab taxi': 'taxi',
  'bolt': 'taxi',
  'gett': 'taxi',
  'freenow': 'taxi',
  'didi': 'taxi',
  'im taxi': 'taxi',
  'macaron taxi': 'taxi',
  'onda taxi': 'taxi',
  'kakao daeri': 'taxi',

  // ── 대중교통 (영문) ──
  'korea rail': 'public_transit',
  'korail pass': 'public_transit',
  't-money': 'public_transit',
  'tmoney': 'public_transit',
  'cashbee': 'public_transit',
  'rail plus': 'public_transit',
  'railplus': 'public_transit',
  'seoul metro': 'public_transit',
  'seoul subway': 'public_transit',
  'busan metro': 'public_transit',
  'incheon metro': 'public_transit',
  'daegu metro': 'public_transit',
  'gwangju metro': 'public_transit',
  'daejeon metro': 'public_transit',
  'arex': 'public_transit',
  'airport railroad': 'public_transit',
  'sinbundang': 'public_transit',
  'gimpo goldline': 'public_transit',
  'jr east': 'public_transit',
  'jr west': 'public_transit',
  'jr central': 'public_transit',
  'suica': 'public_transit',
  'pasmo': 'public_transit',
  'icoca': 'public_transit',
  'shinkansen': 'public_transit',
  'tokyo metro': 'public_transit',
  'oyster card': 'public_transit',
  'tfl': 'public_transit',
  'london underground': 'public_transit',
  'mrt': 'public_transit',
  'octopus card': 'public_transit',
  'bart': 'public_transit',
  'amtrak': 'public_transit',
  'greyhound': 'public_transit',
  'eurostar': 'public_transit',
  'tgv': 'public_transit',
  'db bahn': 'public_transit',
  'trenitalia': 'public_transit',
  'renfe': 'public_transit',

  // ── 주유 / EV 충전 (영문) ──
  'sk energy': 'fuel',
  'gs caltex': 'fuel',
  'gscaltex': 'fuel',
  'hyundai oilbank': 'fuel',
  'soil': 'fuel',
  'sk charging': 'fuel',
  'gs charge': 'fuel',
  'hyundai ev': 'fuel',
  'kia ev': 'fuel',
  'tesla supercharger': 'fuel',
  'tesla': 'fuel',
  'happycharger': 'fuel',
  'chargebi': 'fuel',
  'everon': 'fuel',
  'powercube': 'fuel',
  'chaevi': 'fuel',
  'pluglink': 'fuel',
  'shell': 'fuel',
  'bp': 'fuel',
  'exxon': 'fuel',
  'exxonmobil': 'fuel',
  'chevron': 'fuel',
  'texaco': 'fuel',
  'sunoco': 'fuel',
  'marathon': 'fuel',
  'valero': 'fuel',
  'phillips 66': 'fuel',
  'circle k': 'fuel',
  'speedway': 'fuel',
  'wawa': 'fuel',
  'sheetz': 'fuel',
  'buc-ees': 'fuel',
  'chargepoint': 'fuel',
  'electrify america': 'fuel',
  'evgo': 'fuel',
  'blink charging': 'fuel',

  // ── 주차 (영문) ──
  'parking cloud': 'parking',
  'iparking': 'parking',
  'modu parking': 'parking',
  'kakao t parking': 'parking',
  'naver parking': 'parking',
  'parkingbak': 'parking',
  'spothero': 'parking',
  'parkwhiz': 'parking',
  'parkopedia': 'parking',

  // ── 통행료 (영문) ──
  'hi pass': 'toll',
  'hipass': 'toll',
  'korea expressway': 'toll',
  'ez pass': 'toll',
  'ezpass': 'toll',
  'fastrak': 'toll',
  'sunpass': 'toll',

  // ── 영화 (영문) ──
  'lotte cinema': 'movie',
  'lottecinema': 'movie',
  'cine q': 'movie',
  'primus cinema': 'movie',
  'amc theatres': 'movie',
  'amc theater': 'movie',
  'regal cinemas': 'movie',
  'cinemark': 'movie',
  'fandango': 'movie',
  'atom tickets': 'movie',
  'vue cinemas': 'movie',
  'toho cinemas': 'movie',
  'cineplex': 'movie',

  // ── 스트리밍 (영문 추가) ──
  'watcha': 'streaming',
  'amazon prime': 'streaming',
  'amazon prime video': 'streaming',
  'prime video': 'streaming',
  'naver series on': 'streaming',
  'kakao page': 'streaming',
  'kakaopage': 'streaming',
  'naver webtoon': 'streaming',
  'kakao webtoon': 'streaming',
  'lezhin comics': 'streaming',
  'lezhin': 'streaming',
  'toptoon': 'streaming',
  'audio clip': 'streaming',
  'podbbang': 'streaming',
  'vibe': 'streaming',
  'soribada': 'streaming',
  'naver music': 'streaming',
  'melon': 'streaming',
  'genie music': 'streaming',
  'flo': 'streaming',
  'bugs': 'streaming',
  'bugs music': 'streaming',
  'milli': 'streaming',
  'millie': 'streaming',
  'ridibooks': 'streaming',
  'ridi': 'streaming',
  'laftel': 'streaming',
  'hulu': 'streaming',
  'peacock': 'streaming',
  'peacock tv': 'streaming',
  'paramount': 'streaming',
  'paramount+': 'streaming',
  'paramount plus': 'streaming',
  'funimation': 'streaming',
  'kindle unlimited': 'streaming',
  'kindle': 'streaming',
  'amazon music': 'streaming',
  'pandora music': 'streaming',
  'tidal': 'streaming',
  'deezer': 'streaming',
  'soundcloud': 'streaming',
  'mubi': 'streaming',
  'criterion channel': 'streaming',
  'curiosity stream': 'streaming',
  'max': 'streaming',
  'discovery+': 'streaming',
  'discovery plus': 'streaming',
  'showtime': 'streaming',
  'starz': 'streaming',
  'britbox': 'streaming',
  'plex': 'streaming',

  // ── 구독 / 멤버십 (영문 추가) ──
  'coupang rocket wow': 'subscription',
  'naver plus membership': 'subscription',
  'ssg membership': 'subscription',
  'baemin club': 'subscription',
  'yogi pass': 'subscription',
  'chatgpt plus': 'subscription',
  'openai': 'subscription',
  'claude pro': 'subscription',
  'anthropic': 'subscription',
  'icloud+': 'subscription',
  'icloud plus': 'subscription',
  'dropbox plus': 'subscription',
  'office 365': 'subscription',
  'adobe creative cloud': 'subscription',
  'canva': 'subscription',
  'canva pro': 'subscription',
  'notion plus': 'subscription',
  'slack': 'subscription',
  'zoom': 'subscription',
  'zoom pro': 'subscription',
  'github': 'subscription',
  'github copilot': 'subscription',
  'gitlab': 'subscription',
  'jetbrains': 'subscription',
  'figma': 'subscription',
  'sketch': 'subscription',
  'linear': 'subscription',
  'atlassian': 'subscription',
  'jira': 'subscription',
  'confluence': 'subscription',
  'vercel': 'subscription',
  'netlify': 'subscription',
  'heroku': 'subscription',
  'digitalocean': 'subscription',
  'aws': 'subscription',
  'google cloud': 'subscription',
  'azure': 'subscription',
  'grammarly': 'subscription',
  'lastpass': 'subscription',
  '1password': 'subscription',
  'bitwarden': 'subscription',
  'nordvpn': 'subscription',
  'expressvpn': 'subscription',
  'surfshark': 'subscription',
  'evernote': 'subscription',
  'todoist': 'subscription',
  'bear app': 'subscription',
  'craft docs': 'subscription',
  'obsidian': 'subscription',
  'superhuman': 'subscription',
  'hey email': 'subscription',
  'protonmail': 'subscription',

  // ── 게임 / 앱스토어 / 엔터테인먼트 (영문 추가) ──
  'app store': 'entertainment',
  'nexon': 'entertainment',
  'ncsoft': 'entertainment',
  'netmarble': 'entertainment',
  'kakao games': 'entertainment',
  'kakaogames': 'entertainment',
  'playstation network': 'entertainment',
  'psn': 'entertainment',
  'ps store': 'entertainment',
  'nintendo eshop': 'entertainment',
  'blizzard': 'entertainment',
  'battle.net': 'entertainment',
  'ea games': 'entertainment',
  'electronic arts': 'entertainment',
  'origin': 'entertainment',
  'epic games store': 'entertainment',
  'krafton': 'entertainment',
  'smilegate': 'entertainment',
  'pearl abyss': 'entertainment',
  'wemade': 'entertainment',
  'com2us': 'entertainment',
  'devsisters': 'entertainment',
  'twitch': 'entertainment',
  'twitch.tv': 'entertainment',
  'discord nitro': 'entertainment',
  'discord': 'entertainment',
  'patreon': 'entertainment',
  'gog.com': 'entertainment',
  'humble bundle': 'entertainment',
  'ubisoft': 'entertainment',
  'square enix': 'entertainment',
  'bandai namco': 'entertainment',
  'sega': 'entertainment',
  'capcom': 'entertainment',
  'konami': 'entertainment',
  'supercell': 'entertainment',
  'mihoyo': 'entertainment',
  'hoyoverse': 'entertainment',
  'tencent games': 'entertainment',
  'garena': 'entertainment',
  'everland': 'entertainment',
  'lotte world': 'entertainment',
  'lotteworld': 'entertainment',
  'caribbean bay': 'entertainment',
  'ocean world': 'entertainment',
  'seoul land': 'entertainment',
  'kidzania': 'entertainment',
  'disney world': 'entertainment',
  'disneyland': 'entertainment',
  'universal studios': 'entertainment',
  'legoland': 'entertainment',
  'six flags': 'entertainment',
  'cedar point': 'entertainment',
  'seaworld': 'entertainment',
  'interpark ticket': 'entertainment',
  'yes24 ticket': 'entertainment',
  'ticketlink': 'entertainment',
  'melon ticket': 'entertainment',
  'ticketmaster': 'entertainment',
  'stubhub': 'entertainment',
  'seatgeek': 'entertainment',
  'vivid seats': 'entertainment',
  'eventbrite': 'entertainment',
  'topgolf': 'entertainment',
  'dave and busters': 'entertainment',
  'dave & busters': 'entertainment',
  'round1': 'entertainment',
  'bowlero': 'entertainment',
  'planet fitness': 'entertainment',
  'anytime fitness': 'entertainment',
  'orangetheory': 'entertainment',
  'crossfit': 'entertainment',
  'soulcycle': 'entertainment',
  'equinox': 'entertainment',
  'lifetime fitness': 'entertainment',
  'la fitness': 'entertainment',
  'peloton': 'entertainment',
  'classpass': 'entertainment',

  // ── 통신 (영문) ──
  'sk telecom': 'telecom',
  'skt lte': 'telecom',
  'kt olleh': 'telecom',
  'lg uplus': 'telecom',
  'lg u+': 'telecom',
  'hello mobile': 'telecom',
  'sk broadband': 'telecom',
  'kt internet': 'telecom',
  'lg internet': 'telecom',
  'freet': 'telecom',
  'at&t': 'telecom',
  'verizon': 'telecom',
  't-mobile': 'telecom',
  'tmobile': 'telecom',
  'sprint': 'telecom',
  'comcast': 'telecom',
  'xfinity': 'telecom',
  'spectrum': 'telecom',
  'vodafone': 'telecom',
  'docomo': 'telecom',
  'softbank': 'telecom',
  'o2': 'telecom',
  'ee': 'telecom',
  'three': 'telecom',

  // ── 보험 (영문) ──
  'samsung fire': 'insurance',
  'samsung fire & marine': 'insurance',
  'hyundai marine': 'insurance',
  'hyundai marine & fire': 'insurance',
  'kb insurance': 'insurance',
  'meritz fire': 'insurance',
  'meritz insurance': 'insurance',
  'hanwha life': 'insurance',
  'samsung life': 'insurance',
  'kyobo life': 'insurance',
  'db insurance': 'insurance',
  'heungkuk fire': 'insurance',
  'lina life': 'insurance',
  'axa insurance': 'insurance',
  'aig insurance': 'insurance',
  'chubb insurance': 'insurance',
  'metlife': 'insurance',
  'prudential': 'insurance',
  'state farm': 'insurance',
  'geico': 'insurance',
  'allstate': 'insurance',
  'progressive': 'insurance',
  'usaa': 'insurance',
  'liberty mutual': 'insurance',
  'farmers insurance': 'insurance',
  'nationwide': 'insurance',
  'aetna': 'insurance',
  'cigna': 'insurance',
  'united healthcare': 'insurance',
  'blue cross': 'insurance',
  'blue shield': 'insurance',
  'humana': 'insurance',
  'kaiser permanente': 'insurance',

  // ── 병원 / 의료 (영문) ──
  'samsung seoul hospital': 'hospital',
  'seoul asan hospital': 'hospital',
  'asan medical center': 'hospital',
  'severance': 'hospital',
  'severance hospital': 'hospital',
  'seoul national university hospital': 'hospital',
  'snuh': 'hospital',
  'korea university hospital': 'hospital',
  'st mary hospital': 'hospital',
  'chungang hospital': 'hospital',
  'gangnam severance': 'hospital',
  'samsung medical center': 'hospital',
  'clinic': 'hospital',
  'dental': 'hospital',
  'dentist': 'hospital',
  'dermatology': 'hospital',
  'ophthalmology': 'hospital',
  'orthopedics': 'hospital',

  // ── 약국 (영문) ──
  'pharmacy': 'pharmacy',
  'drugstore': 'pharmacy',
  'onnuri pharmacy': 'pharmacy',
  'cvs': 'pharmacy',
  'cvs pharmacy': 'pharmacy',
  'walgreens': 'pharmacy',
  'rite aid': 'pharmacy',
  'riteaid': 'pharmacy',
  'boots pharmacy': 'pharmacy',
  'matsumoto kiyoshi': 'pharmacy',
  'matsukiyo': 'pharmacy',

  // ── 동물병원 (영문) ──
  'veterinary': 'medical',
  'vet clinic': 'medical',
  'animal hospital': 'medical',
  'pet clinic': 'medical',
  'pet hospital': 'medical',
  'banfield': 'medical',
  'vca animal': 'medical',

  // ── 학원 / 교육 (영문) ──
  'ybm': 'academy',
  'hackers': 'academy',
  'siwonschool': 'academy',
  'siwon school': 'academy',
  'yanadoo': 'academy',
  'speaking max': 'academy',
  'wework': 'academy',
  'fast five': 'academy',
  'fastfive': 'academy',
  'study cafe': 'academy',
  'kumon': 'academy',
  'sylvan learning': 'academy',
  'kaplan': 'academy',
  'princeton review': 'academy',
  'berlitz': 'academy',

  // ── 온라인 교육 (영문) ──
  'class101': 'education',
  'fastcampus': 'education',
  'fast campus': 'education',
  'inflearn': 'education',
  'eduwill': 'education',
  'megastudy': 'education',
  'etoos': 'education',
  'daesung myimac': 'education',
  'taling': 'education',
  'kmong': 'education',
  'soomgo': 'education',
  'programmers': 'education',
  'codeit': 'education',
  'elice': 'education',
  'nomad coders': 'education',
  'zerobase': 'education',
  'wecode': 'education',
  'skillshare': 'education',
  'masterclass': 'education',
  'linkedin learning': 'education',
  'khan academy': 'education',
  'edx': 'education',
  'codecademy': 'education',
  'datacamp': 'education',
  'pluralsight': 'education',
  'treehouse': 'education',
  'brilliant': 'education',
  'babbel': 'education',
  'rosetta stone': 'education',
  'busuu': 'education',
  'memrise': 'education',

  // ── 도서 (영문) ──
  'kyobo bookstore': 'books',
  'kyobobook': 'books',
  'aladin': 'books',
  'aladdin': 'books',
  'youngpoong': 'books',
  'bandi & luni': 'books',
  'bookslibro': 'books',
  'ridi select': 'books',
  'barnes noble': 'books',
  'barnes & noble': 'books',
  'kindle store': 'books',
  'apple books': 'books',
  'google books': 'books',
  'libro': 'books',
  'waterstones': 'books',
  'powell\'s books': 'books',
  'book depository': 'books',

  // ── 항공 (영문 추가) ──
  'air seoul': 'airline',
  'air busan': 'airline',
  'air premia': 'airline',
  'eastar jet': 'airline',
  'fly gangwon': 'airline',
  'hi air': 'airline',
  'southwest': 'airline',
  'southwest airlines': 'airline',
  'jetblue': 'airline',
  'alaska airlines': 'airline',
  'spirit airlines': 'airline',
  'frontier airlines': 'airline',
  'hawaiian airlines': 'airline',
  'allegiant air': 'airline',
  'air canada': 'airline',
  'westjet': 'airline',
  'ryanair': 'airline',
  'easyjet': 'airline',
  'vueling': 'airline',
  'wizz air': 'airline',
  'norwegian air': 'airline',
  'finnair': 'airline',
  'swiss air': 'airline',
  'klm': 'airline',
  'iberia': 'airline',
  'sas': 'airline',
  'tap portugal': 'airline',
  'aegean airlines': 'airline',
  'lot polish': 'airline',
  'china eastern': 'airline',
  'china southern': 'airline',
  'air china': 'airline',
  'hainan airlines': 'airline',
  'garuda indonesia': 'airline',
  'malaysia airlines': 'airline',
  'philippine airlines': 'airline',
  'vietnam airlines': 'airline',
  'cebu pacific': 'airline',
  'air new zealand': 'airline',
  'qantas': 'airline',
  'virgin atlantic': 'airline',
  'etihad': 'airline',
  'oman air': 'airline',
  'saudia': 'airline',
  'royal jordanian': 'airline',
  'el al': 'airline',
  'ethiopian airlines': 'airline',
  'south african airways': 'airline',
  'copa airlines': 'airline',
  'latam': 'airline',
  'avianca': 'airline',
  'azul airlines': 'airline',
  'skyscanner air': 'airline',
  'google flights': 'airline',

  // ── 숙박 (영문 추가) ──
  'yanolja': 'hotel',
  'goodchoice': 'hotel',
  'hilton': 'hotel',
  'hilton garden': 'hotel',
  'hampton inn': 'hotel',
  'doubletree': 'hotel',
  'embassy suites': 'hotel',
  'waldorf astoria': 'hotel',
  'marriott': 'hotel',
  'marriott bonvoy': 'hotel',
  'courtyard marriott': 'hotel',
  'residence inn': 'hotel',
  'springhill suites': 'hotel',
  'fairfield inn': 'hotel',
  'aloft': 'hotel',
  'element': 'hotel',
  'w hotel': 'hotel',
  'st regis': 'hotel',
  'luxury collection': 'hotel',
  'tribute portfolio': 'hotel',
  'le meridien': 'hotel',
  'westin': 'hotel',
  'sheraton': 'hotel',
  'hyatt': 'hotel',
  'hyatt regency': 'hotel',
  'grand hyatt': 'hotel',
  'park hyatt': 'hotel',
  'andaz': 'hotel',
  'intercontinental': 'hotel',
  'holiday inn': 'hotel',
  'holiday inn express': 'hotel',
  'crowne plaza': 'hotel',
  'kimpton': 'hotel',
  'ihg': 'hotel',
  'four seasons': 'hotel',
  'ritz carlton': 'hotel',
  'ritz-carlton': 'hotel',
  'mandarin oriental': 'hotel',
  'peninsula': 'hotel',
  'aman': 'hotel',
  'rosewood': 'hotel',
  'six senses': 'hotel',
  'banyan tree': 'hotel',
  'shangri-la': 'hotel',
  'shangrila': 'hotel',
  'sofitel': 'hotel',
  'accor': 'hotel',
  'ibis': 'hotel',
  'novotel': 'hotel',
  'pullman': 'hotel',
  'best western': 'hotel',
  'motel 6': 'hotel',
  'super 8': 'hotel',
  'days inn': 'hotel',
  'la quinta': 'hotel',
  'comfort inn': 'hotel',
  'quality inn': 'hotel',
  'choice hotels': 'hotel',
  'wyndham': 'hotel',
  'radisson': 'hotel',
  'lotte hotel': 'hotel',
  'shilla hotel': 'hotel',
  'josun hotel': 'hotel',
  'josun palace': 'hotel',
  'walkerhill': 'hotel',
  'kensington': 'hotel',
  'hanwha resort': 'hotel',
  'daemyung resort': 'hotel',
  'sono hotel': 'hotel',
  'fairmont': 'hotel',
  'ambassador': 'hotel',
  'ramada': 'hotel',
  'conrad': 'hotel',
  'oakwood': 'hotel',
  'somerset': 'hotel',
  'fraser': 'hotel',
  'nine tree': 'hotel',
  'glad hotel': 'hotel',
  'vrbo': 'hotel',
  'hostelworld': 'hotel',
  'trivago': 'hotel',

  // ── 여행 (영문) ──
  'hanatour': 'travel',
  'hana tour': 'travel',
  'modetour': 'travel',
  'mode tour': 'travel',
  'norang pungson': 'travel',
  'yellow balloon': 'travel',
  'chamjoeun': 'travel',
  'skyscanner': 'travel',
  'triple': 'travel',
  'myrealtrip': 'travel',
  'my real trip': 'travel',
  'tavi': 'travel',
  'interpark tour': 'travel',
  'waug': 'travel',
  'tourbis': 'travel',
  'tourtips': 'travel',
  'hanjin tour': 'travel',
  'lotte tour': 'travel',
  'online tour': 'travel',
  'webtour': 'travel',
  'viator': 'travel',
  'getyourguide': 'travel',
  'get your guide': 'travel',
  'traveloka': 'travel',
  'hopper': 'travel',
  'momondo': 'travel',
  'google travel': 'travel',
  'tripadvisor': 'travel',
  'lonely planet': 'travel',
  'orbitz': 'travel',
  'priceline': 'travel',
  'travelocity': 'travel',
  'cheapoair': 'travel',
  'kiwi.com': 'travel',
  'omio': 'travel',

  // ── 공과금 / 관리비 (영문) ──
  'kepco': 'utilities',
  'korea electric': 'utilities',
  'korea gas': 'utilities',
  'city gas': 'utilities',
  'water bill': 'utilities',
  'management fee': 'utilities',
  'nhis': 'utilities',
  'national pension': 'utilities',

  // ── 렌터카 / 차량 (영문) ──
  'greencar': 'transportation',
  'green car': 'transportation',
  'kakao t rental': 'transportation',
  'lotte rental': 'transportation',
  'lotte rent-a-car': 'transportation',
  'sk rental': 'transportation',
  'hyundai rental': 'transportation',
  'jeju rental': 'transportation',
  'aj rental': 'transportation',
  'car center': 'transportation',
  'tire bank': 'transportation',
  'auto oasis': 'transportation',
  'autoglass': 'transportation',
  'encar': 'transportation',
  'k car': 'transportation',
  'hey dealer': 'transportation',
  'heydealer': 'transportation',
  'carnac': 'transportation',
  'tire pro': 'transportation',
  'kumho tire': 'transportation',
  'hankook tire': 'transportation',
  'nexen tire': 'transportation',
  'blue hands': 'transportation',
  'autoq': 'transportation',
  'speedmate': 'transportation',
  'polestar': 'transportation',
  'hertz': 'transportation',
  'avis': 'transportation',
  'enterprise': 'transportation',
  'enterprise rent-a-car': 'transportation',
  'budget': 'transportation',
  'sixt': 'transportation',
  'national car rental': 'transportation',
  'dollar rent': 'transportation',
  'thrifty': 'transportation',
  'zipcar': 'transportation',
  'turo': 'transportation',
  'getaround': 'transportation',
  'jiffy lube': 'transportation',
  'firestone': 'transportation',
  'midas': 'transportation',
  'pep boys': 'transportation',
  'autozone': 'transportation',
  'o\'reilly auto': 'transportation',
  'advance auto': 'transportation',
  'napa auto': 'transportation',
  'carmax': 'transportation',
  'carvana': 'transportation',
  'vroom': 'transportation',

  // ════════════════════════════════════════════════════════════════════
  // ── CORPORATE / LEGAL ENTITY NAMES (법인명) ──
  // ════════════════════════════════════════════════════════════════════

  '씨제이푸드빌': 'dining.restaurant',
  'cj foodville': 'dining.restaurant',
  'cj푸드빌': 'dining.restaurant',
  '에스피씨': 'dining.cafe',
  'spc': 'dining.cafe',
  'spc그룹': 'dining.cafe',
  '에스피씨삼립': 'dining.cafe',
  'spc samlip': 'dining.cafe',
  '제너시스비비큐': 'dining.delivery',
  'genesis bbq': 'dining.delivery',
  '제이와이네트웍': 'dining.restaurant',
  '할리스에프앤비': 'dining.cafe',
  'hollys f&b': 'dining.cafe',
  'gongcha korea': 'dining.cafe',
  'cj올리브네트웍스': 'offline_shopping',
  'cj olive networks': 'offline_shopping',
  'cj olivenetworks': 'offline_shopping',
  '롯데쇼핑': 'department_store',
  'lotte shopping': 'department_store',
  '현대백화점면세점': 'offline_shopping',
  'hyundai duty free': 'offline_shopping',
  '신세계디에프': 'offline_shopping',
  'shinsegae df': 'offline_shopping',
  'shinsegae duty free': 'offline_shopping',
  '신세계인터내셔날': 'fashion',
  'shinsegae international': 'fashion',
  '한섬': 'fashion',
  'thehandsome': 'fashion',
  '코오롱인더스트리': 'fashion',
  'kolon industries': 'fashion',
  '이랜드': 'fashion',
  'e-land': 'fashion',
  'eland': 'fashion',
  '에프앤에프': 'fashion',
  'f&f': 'fashion',
  'fnf': 'fashion',
  '삼성물산패션': 'fashion',
  'samsung c&t fashion': 'fashion',
  '삼양식품': 'grocery.supermarket',
  'samyang foods': 'grocery.supermarket',
  '농심': 'grocery.supermarket',
  'nongshim': 'grocery.supermarket',
  '씨제이제일제당': 'grocery.supermarket',
  'cj cheiljedang': 'grocery.supermarket',
  'cj제일제당': 'grocery.supermarket',
  '하이트진로': 'dining.restaurant',
  'hitejinro': 'dining.restaurant',
  'hite jinro': 'dining.restaurant',
  '오비맥주': 'dining.restaurant',
  'ob beer': 'dining.restaurant',
  '롯데칠성': 'grocery.supermarket',
  'lotte chilsung': 'grocery.supermarket',
  '풀무원': 'grocery.supermarket',
  'pulmuone': 'grocery.supermarket',
  '오뚜기': 'grocery.supermarket',
  'ottogi': 'grocery.supermarket',
  '동원에프앤비': 'grocery.supermarket',
  'dongwon f&b': 'grocery.supermarket',
  '대상': 'grocery.supermarket',
  'daesang': 'grocery.supermarket',
  '빙그레': 'grocery.supermarket',
  'binggrae': 'grocery.supermarket',
  '해태제과': 'grocery.supermarket',
  'haitai': 'grocery.supermarket',
  '크라운제과': 'grocery.supermarket',
  'crown confectionery': 'grocery.supermarket',
  '롯데제과': 'grocery.supermarket',
  'lotte confectionery': 'grocery.supermarket',
  '오리온': 'grocery.supermarket',
  'orion': 'grocery.supermarket',
  '매일유업': 'grocery.supermarket',
  'maeil dairies': 'grocery.supermarket',
  '남양유업': 'grocery.supermarket',
  'namyang dairy': 'grocery.supermarket',
  '서울우유': 'grocery.supermarket',
  'seoul milk': 'grocery.supermarket',
  '카카오': 'online_shopping',
  'kakao': 'online_shopping',
  '네이버': 'online_shopping',
  'naver': 'online_shopping',
  '우아한형제들': 'dining.delivery',
  'woowa brothers': 'dining.delivery',
  '쿠팡주식회사': 'online_shopping',
  'coupang inc': 'online_shopping',
  '비바리퍼블리카': 'online_shopping',
  'viva republica': 'online_shopping',
  '토스': 'online_shopping',
  'toss': 'online_shopping',
  '야놀자주식회사': 'hotel',
  '위대한상상': 'hotel',
  'great imagination': 'hotel',

  // ════════════════════════════════════════════════════════════════════
  // ── JAPANESE MERCHANT NAMES (일본 여행) ──
  // ════════════════════════════════════════════════════════════════════

  'セブンイレブン': 'convenience_store',
  'セブン-イレブン': 'convenience_store',
  'ファミリーマート': 'convenience_store',
  'ファミマ': 'convenience_store',
  'ローソン': 'convenience_store',
  'ミニストップ': 'convenience_store',
  'デイリーヤマザキ': 'convenience_store',
  'ニューデイズ': 'convenience_store',
  'family mart': 'convenience_store',
  'familymart': 'convenience_store',
  'lawson': 'convenience_store',

  'すき家': 'dining.fast_food',
  '吉野家': 'dining.fast_food',
  '松屋': 'dining.fast_food',
  'マクドナルド': 'dining.fast_food',
  'モスバーガー': 'dining.fast_food',
  'mos burger': 'dining.fast_food',
  'mosburger': 'dining.fast_food',
  'フレッシュネス': 'dining.fast_food',
  'freshness burger': 'dining.fast_food',
  'てんや': 'dining.fast_food',
  'tenya': 'dining.fast_food',
  '丸亀製麺': 'dining.fast_food',
  'marugame seimen': 'dining.fast_food',
  'marugame': 'dining.fast_food',
  'なか卯': 'dining.fast_food',
  'nakau': 'dining.fast_food',
  '天下一品': 'dining.restaurant',
  'tenkaippin': 'dining.restaurant',
  '一蘭': 'dining.restaurant',
  'ichiran': 'dining.restaurant',
  '一風堂': 'dining.restaurant',
  'ippudo': 'dining.restaurant',
  'sukiya': 'dining.fast_food',
  'yoshinoya': 'dining.fast_food',
  'matsuya': 'dining.fast_food',
  'coco ichibanya': 'dining.restaurant',
  'cocoichi': 'dining.restaurant',
  'ココイチ': 'dining.restaurant',
  'CoCo壱番屋': 'dining.restaurant',
  '餃子の王将': 'dining.restaurant',
  'ohsho': 'dining.restaurant',
  'gyoza no ohsho': 'dining.restaurant',
  'サイゼリヤ': 'dining.restaurant',
  'saizeriya': 'dining.restaurant',
  'ガスト': 'dining.restaurant',
  'gusto': 'dining.restaurant',
  'ジョナサン': 'dining.restaurant',
  'jonathan': 'dining.restaurant',
  'デニーズ': 'dining.restaurant',
  'ロイヤルホスト': 'dining.restaurant',
  'royal host': 'dining.restaurant',
  'びっくりドンキー': 'dining.restaurant',
  'bikkuri donkey': 'dining.restaurant',

  'スターバックス': 'dining.cafe',
  'タリーズ': 'dining.cafe',
  'tully\'s': 'dining.cafe',
  'tullys': 'dining.cafe',
  'ドトール': 'dining.cafe',
  'doutor': 'dining.cafe',
  'コメダ珈琲': 'dining.cafe',
  'komeda': 'dining.cafe',
  'komeda coffee': 'dining.cafe',
  'エクセルシオール': 'dining.cafe',
  'サンマルク': 'dining.cafe',
  'st marc cafe': 'dining.cafe',

  'ドンキホーテ': 'offline_shopping',
  'ドン・キホーテ': 'offline_shopping',
  'don quijote': 'offline_shopping',
  'donki': 'offline_shopping',
  'donkihote': 'offline_shopping',
  'daiso japan': 'offline_shopping',
  'ダイソー': 'offline_shopping',
  'ユニクロ': 'fashion',
  'uniqlo japan': 'fashion',
  'gu': 'fashion',
  'ジーユー': 'fashion',
  'muji': 'offline_shopping',
  '無印良品': 'offline_shopping',
  'mujirushi': 'offline_shopping',
  'tokyu hands': 'offline_shopping',
  '東急ハンズ': 'offline_shopping',
  'loft': 'offline_shopping',
  'ロフト': 'offline_shopping',
  'bic camera': 'offline_shopping',
  'ビックカメラ': 'offline_shopping',
  'yodobashi': 'offline_shopping',
  'ヨドバシカメラ': 'offline_shopping',
  'yamada denki': 'offline_shopping',
  'ヤマダ電機': 'offline_shopping',
  'kojima': 'offline_shopping',
  'コジマ': 'offline_shopping',
  'edion': 'offline_shopping',
  'エディオン': 'offline_shopping',
  'nojima': 'offline_shopping',
  'ノジマ': 'offline_shopping',
  'ksdenki': 'offline_shopping',
  'ケーズデンキ': 'offline_shopping',
  'animate': 'offline_shopping',
  'アニメイト': 'offline_shopping',
  'mandarake': 'offline_shopping',
  'まんだらけ': 'offline_shopping',
  'book off': 'offline_shopping',
  'ブックオフ': 'offline_shopping',
  'hard off': 'offline_shopping',
  'ハードオフ': 'offline_shopping',
  'tsutaya': 'offline_shopping',
  'ツタヤ': 'offline_shopping',

  'aeon': 'grocery.supermarket',
  'イオン': 'grocery.supermarket',
  'イトーヨーカドー': 'grocery.supermarket',
  'ito yokado': 'grocery.supermarket',
  'ライフ': 'grocery.supermarket',
  'life supermarket': 'grocery.supermarket',
  'maruetsu': 'grocery.supermarket',
  'マルエツ': 'grocery.supermarket',
  'サミット': 'grocery.supermarket',
  'summit': 'grocery.supermarket',
  'ok store': 'grocery.supermarket',
  'オーケー': 'grocery.supermarket',
  'gyomu super': 'grocery.supermarket',
  '業務スーパー': 'grocery.supermarket',

  'マツモトキヨシ': 'pharmacy',
  'ウエルシア': 'pharmacy',
  'welcia': 'pharmacy',
  'ツルハ': 'pharmacy',
  'tsuruha': 'pharmacy',
  'サンドラッグ': 'pharmacy',
  'sundrug': 'pharmacy',
  'ココカラファイン': 'pharmacy',
  'cocokara fine': 'pharmacy',

  'jr東日本': 'public_transit',
  'jr西日本': 'public_transit',
  'jr東海': 'public_transit',
  'jr九州': 'public_transit',
  'jr北海道': 'public_transit',
  '東京メトロ': 'public_transit',
  '都営地下鉄': 'public_transit',
  '大阪メトロ': 'public_transit',
  '新幹線': 'public_transit',

  'apa hotel': 'hotel',
  'アパホテル': 'hotel',
  'toyoko inn': 'hotel',
  '東横イン': 'hotel',
  'route inn': 'hotel',
  'ルートイン': 'hotel',
  'dormy inn': 'hotel',
  'ドーミーイン': 'hotel',
  'super hotel': 'hotel',
  'スーパーホテル': 'hotel',
  'ホテルモントレ': 'hotel',
  'hotel monterey': 'hotel',
  '星野リゾート': 'hotel',
  'hoshino resort': 'hotel',

  // ════════════════════════════════════════════════════════════════════
  // ── COMMON GENERIC KEYWORDS (일반 키워드) ──
  // ════════════════════════════════════════════════════════════════════

  '식당': 'dining.restaurant',
  '레스토랑': 'dining.restaurant',
  '고깃집': 'dining.restaurant',
  '포차': 'dining.restaurant',
  'restaurant': 'dining.restaurant',
  'bistro': 'dining.restaurant',
  'brasserie': 'dining.restaurant',
  'trattoria': 'dining.restaurant',
  'pizzeria': 'dining.restaurant',
  'tavern': 'dining.restaurant',
  'gastropub': 'dining.restaurant',
  'eatery': 'dining.restaurant',
  'grill': 'dining.restaurant',
  'diner': 'dining.restaurant',
  'cafe': 'dining.cafe',
  'coffee': 'dining.cafe',
  'bakery': 'dining.cafe',
  'patisserie': 'dining.cafe',
  'boulangerie': 'dining.cafe',
  '마트': 'grocery.supermarket',
  '슈퍼': 'grocery.supermarket',
  '슈퍼마켓': 'grocery.supermarket',
  'supermarket': 'grocery.supermarket',
  'grocery': 'grocery.supermarket',
  'mart': 'grocery.supermarket',
  '세탁소': 'offline_shopping',
  '미용실': 'offline_shopping',
  '헤어샵': 'offline_shopping',
  '헤어살롱': 'offline_shopping',
  'hair salon': 'offline_shopping',
  'barbershop': 'offline_shopping',
  'barber': 'offline_shopping',
  '네일샵': 'offline_shopping',
  'nail salon': 'offline_shopping',
  '피부관리': 'offline_shopping',
  'spa': 'offline_shopping',
  'optical': 'offline_shopping',
  'optician': 'offline_shopping',
  '화원': 'offline_shopping',
  'florist': 'offline_shopping',
  'flower shop': 'offline_shopping',
  '철물점': 'offline_shopping',
  'hardware': 'offline_shopping',
  'stationery': 'offline_shopping',
  '인쇄소': 'offline_shopping',
  'print shop': 'offline_shopping',
  '복사': 'offline_shopping',
  '사진관': 'offline_shopping',
  'photo studio': 'offline_shopping',
  '스튜디오': 'offline_shopping',
  '자전거': 'offline_shopping',
  'bicycle shop': 'offline_shopping',
  'bike shop': 'offline_shopping',
  '이발소': 'offline_shopping',
  '네일아트': 'offline_shopping',
  '타투': 'offline_shopping',
  'tattoo': 'offline_shopping',
  '피어싱': 'offline_shopping',
  'piercing': 'offline_shopping',
  'laundromat': 'offline_shopping',
  'laundry': 'offline_shopping',
  'dry cleaning': 'offline_shopping',
  'tailor': 'offline_shopping',
  'jeweler': 'offline_shopping',
  'jewelry': 'offline_shopping',
  'watch repair': 'offline_shopping',
  'locksmith': 'offline_shopping',
  'cobbler': 'offline_shopping',
  'shoe repair': 'offline_shopping',
  'alteration': 'offline_shopping',
  'frameshop': 'offline_shopping',
  'art supply': 'offline_shopping',
  'pet store': 'offline_shopping',
  'pet shop': 'offline_shopping',
  'garden center': 'offline_shopping',
  'nursery': 'offline_shopping',
  '인테리어': 'offline_shopping',
  '가구': 'offline_shopping',
  'furniture': 'offline_shopping',

  // ── 추가 한국 프랜차이즈 / 체인 ──
  '원할머니': 'dining.restaurant',
  '김밥나라': 'dining.restaurant',
  '종로김밥': 'dining.restaurant',
  '고봉민': 'dining.fast_food',
  '바르다': 'dining.fast_food',
  '이삭': 'dining.fast_food',
  '본도시락': 'dining.fast_food',
  'bondosirak': 'dining.fast_food',
  '한솥도시락': 'dining.restaurant',
  '편스토랑': 'dining.restaurant',
  '더밥': 'dining.restaurant',
  '미분당': 'dining.restaurant',
  '시골집': 'dining.restaurant',
  '원조할매': 'dining.restaurant',
  '옛날': 'dining.restaurant',
  '전통': 'dining.restaurant',
  '감나무': 'dining.restaurant',
  '산골': 'dining.restaurant',
  '시골': 'dining.restaurant',
  '고향': 'dining.restaurant',
  '왕돈까스': 'dining.restaurant',
  '홍익돈까스': 'dining.restaurant',
  '돈까스클럽': 'dining.restaurant',
  '카츠요이': 'dining.restaurant',
  '서가앤쿡': 'dining.restaurant',
  '빅마마': 'dining.restaurant',
  '미스사이공': 'dining.restaurant',
  '포베이': 'dining.restaurant',
  '포호아': 'dining.restaurant',
  '에머이': 'dining.restaurant',
  '스파이시인디아': 'dining.restaurant',
  '간장게장': 'dining.restaurant',
  '양념게장': 'dining.restaurant',
  '닭꼬치': 'dining.restaurant',
  '꼬치': 'dining.restaurant',
  '어묵바': 'dining.restaurant',
  '오뎅바': 'dining.restaurant',
  '대포집': 'dining.restaurant',
  '소주방': 'dining.restaurant',
  '맥주집': 'dining.restaurant',
  '막걸리': 'dining.restaurant',
  '전집': 'dining.restaurant',
  '파전': 'dining.restaurant',
  '해물파전': 'dining.restaurant',
  '닭발': 'dining.restaurant',
  '곱창전골': 'dining.restaurant',
  '양곱창': 'dining.restaurant',
  '짚불구이': 'dining.restaurant',
  '장어구이': 'dining.restaurant',
  '민물매운탕': 'dining.restaurant',
  '대구탕': 'dining.restaurant',
  '알탕': 'dining.restaurant',
  '아구': 'dining.restaurant',
  '생선회': 'dining.restaurant',
  '광어': 'dining.restaurant',
  '참치': 'dining.restaurant',
  '연어': 'dining.restaurant',
  '타코야끼': 'dining.fast_food',
  '붕어빵': 'dining.fast_food',
  '호떡': 'dining.fast_food',
  '계란빵': 'dining.fast_food',
  '떡': 'dining.fast_food',
  '와플': 'dining.cafe',
  '크레페': 'dining.cafe',
  '팥빙수': 'dining.cafe',
  '빙수': 'dining.cafe',
  '아이스크림': 'dining.cafe',
  '소프트아이스크림': 'dining.cafe',
  '츄러스': 'dining.cafe',
  '에그타르트': 'dining.cafe',
  '크로와상': 'dining.cafe',
  '샌드위치': 'dining.fast_food',
  '핫플': 'dining.restaurant',
  '맛집': 'dining.restaurant',

  // ── 추가 치킨 브랜드 ──
  '깐부치킨': 'dining.delivery',
  '치킨플러스': 'dining.delivery',
  '또래오래치킨': 'dining.delivery',
  '오븐마루': 'dining.delivery',
  '신통치킨': 'dining.delivery',
  '스모프치킨': 'dining.delivery',
  '티바두마리치킨': 'dining.delivery',
  '여한치킨': 'dining.delivery',
  '투존치킨': 'dining.delivery',
  '또봉이통닭': 'dining.delivery',
  '피자에땅': 'dining.delivery',
  '피자헤븐': 'dining.delivery',

  // ── 반려동물 (추가) ──
  '애견용품점': 'offline_shopping',
  '펫마트': 'offline_shopping',
  '동물약국': 'offline_shopping',
  '멍냥마켓': 'offline_shopping',
  'pet mart': 'offline_shopping',

  // ── 추가 편의점 변형 ──
  'cu편의점': 'convenience_store',
  'gs편의점': 'convenience_store',
  'gs25편의점': 'convenience_store',
  '세븐편의점': 'convenience_store',
  '이마트편의점': 'convenience_store',

  // ── 중국 브랜드 / 관련 (해외결제) ──
  'alipay': 'online_shopping',
  'wechat pay': 'online_shopping',
  'taobao': 'online_shopping',
  'tmall': 'online_shopping',
  'meituan': 'dining.delivery',
  'ele.me': 'dining.delivery',
  'dianping': 'dining.restaurant',
  'ctrip': 'travel',

  // ── 동남아 브랜드 (해외여행) ──
  'gojek': 'taxi',
  'be group': 'taxi',
  'maxim': 'taxi',
  'indriver': 'taxi',
  'line man': 'dining.delivery',
  'lineman': 'dining.delivery',
  'robinhood': 'dining.delivery',
  'central': 'offline_shopping',
  'robinson': 'offline_shopping',
  'the mall': 'offline_shopping',
  'siam paragon': 'offline_shopping',
  'terminal 21': 'offline_shopping',
  'big c': 'grocery.supermarket',
  'tops market': 'grocery.supermarket',
  'lotus\'s': 'grocery.supermarket',
  'makro': 'grocery.supermarket',
  'villa market': 'grocery.supermarket',

  // ── 유럽 브랜드 (해외여행) ──
  'monoprix': 'grocery.supermarket',
  'franprix': 'grocery.supermarket',
  'leclerc': 'grocery.supermarket',
  'intermarche': 'grocery.supermarket',
  'auchan': 'grocery.supermarket',
  'edeka': 'grocery.supermarket',
  'rewe': 'grocery.supermarket',
  'netto': 'grocery.supermarket',
  'penny': 'grocery.supermarket',
  'mercadona': 'grocery.supermarket',
  'el corte ingles': 'department_store',
  'galeries lafayette': 'department_store',
  'harrods': 'department_store',
  'selfridges': 'department_store',
  'john lewis': 'department_store',
  'printemps': 'department_store',
  'bon marche': 'department_store',
  'la rinascente': 'department_store',
  'kadewe': 'department_store',
  'fnac': 'offline_shopping',
  'media markt': 'offline_shopping',
  'saturn': 'offline_shopping',
  'dm': 'pharmacy',
  'rossmann': 'pharmacy',
  'boots': 'pharmacy',
  'müller': 'pharmacy',
  'superdrug': 'pharmacy',

  // ── 호주 / 뉴질랜드 브랜드 ──
  'coles': 'grocery.supermarket',
  'iga': 'grocery.supermarket',
  'countdown': 'grocery.supermarket',
  'pak n save': 'grocery.supermarket',
  'new world': 'grocery.supermarket',
  'bunnings': 'offline_shopping',
  'kmart': 'offline_shopping',
  'myer': 'department_store',
  'david jones': 'department_store',

  // ── 결제/금융 식별자 ──
  'paypal': 'online_shopping',
  'stripe': 'online_shopping',
  'square': 'online_shopping',
  'klarna': 'online_shopping',
  'afterpay': 'online_shopping',
  'affirm': 'online_shopping',
  'venmo': 'online_shopping',
  'cash app': 'online_shopping',
  'google pay': 'online_shopping',
  'gpay': 'online_shopping',
};
