/**
 * Static map of well-known Korean merchant names to canonical category IDs.
 * Category IDs follow the taxonomy defined in packages/rules/data/categories.yaml.
 * Higher-specificity matches take priority during lookup.
 */
export const MERCHANT_KEYWORDS: Record<string, string> = {
  // ── 카페 / 커피 ──
  '스타벅스': 'dining.cafe',
  'starbucks': 'dining.cafe',
  '투썸플레이스': 'dining.cafe',
  'twosome': 'dining.cafe',
  '이디야': 'dining.cafe',
  '빽다방': 'dining.cafe',
  '메가커피': 'dining.cafe',
  '메가MGC': 'dining.cafe',
  '컴포즈커피': 'dining.cafe',
  '할리스': 'dining.cafe',
  '폴바셋': 'dining.cafe',
  '커피빈': 'dining.cafe',
  'coffee bean': 'dining.cafe',
  '파스쿠찌': 'dining.cafe',
  '더벤티': 'dining.cafe',
  '카페베네': 'dining.cafe',
  '탐앤탐스': 'dining.cafe',
  '엔제리너스': 'dining.cafe',
  '블루보틀': 'dining.cafe',
  '커피스미스': 'dining.cafe',
  '매머드커피': 'dining.cafe',
  '공차': 'dining.cafe',
  '쥬시': 'dining.cafe',

  // ── 베이커리 / 디저트 ──
  '파리바게뜨': 'dining.cafe',
  '뚜레쥬르': 'dining.cafe',
  '던킨': 'dining.cafe',
  '크리스피크림': 'dining.cafe',
  '배스킨라빈스': 'dining.cafe',
  '설빙': 'dining.cafe',
  '성심당': 'dining.cafe',
  '나뚜루': 'dining.cafe',

  // ── 패스트푸드 ──
  '맥도날드': 'dining.fast_food',
  'mcdonald': 'dining.fast_food',
  '버거킹': 'dining.fast_food',
  'burger king': 'dining.fast_food',
  '롯데리아': 'dining.fast_food',
  '맘스터치': 'dining.fast_food',
  'kfc': 'dining.fast_food',
  '서브웨이': 'dining.fast_food',
  'subway': 'dining.fast_food',
  '파파이스': 'dining.fast_food',
  '노브랜드버거': 'dining.fast_food',
  '쉐이크쉑': 'dining.fast_food',
  '파이브가이즈': 'dining.fast_food',
  '이삭토스트': 'dining.fast_food',

  // ── 치킨 / 피자 ──
  '교촌치킨': 'dining.delivery',
  'bbq치킨': 'dining.delivery',
  '네네치킨': 'dining.delivery',
  '굽네치킨': 'dining.delivery',
  'bhc': 'dining.delivery',
  '또래오래': 'dining.delivery',
  '호식이두마리': 'dining.delivery',
  '처갓집': 'dining.delivery',
  '푸라닭': 'dining.delivery',
  '도미노피자': 'dining.delivery',
  'domino': 'dining.delivery',
  '피자헛': 'dining.delivery',
  'pizza hut': 'dining.delivery',
  '미스터피자': 'dining.delivery',
  '피자알볼로': 'dining.delivery',
  '파파존스': 'dining.delivery',

  // ── 음식 배달 ──
  '배달의민족': 'dining.delivery',
  '배민': 'dining.delivery',
  '요기요': 'dining.delivery',
  '쿠팡이츠': 'dining.delivery',
  '땡겨요': 'dining.delivery',

  // ── 외식 체인 ──
  '아웃백': 'dining.restaurant',
  'outback': 'dining.restaurant',
  '빕스': 'dining.restaurant',
  'vips': 'dining.restaurant',
  '애슐리': 'dining.restaurant',
  '매드포갈릭': 'dining.restaurant',
  '한솥': 'dining.restaurant',
  '본죽': 'dining.restaurant',
  '김밥천국': 'dining.restaurant',
  '김가네': 'dining.restaurant',
  '놀부': 'dining.restaurant',
  '더본코리아': 'dining.restaurant',
  '새마을식당': 'dining.restaurant',
  '백년옥': 'dining.restaurant',
  '원할머니보쌈': 'dining.restaurant',
  '한신포차': 'dining.restaurant',
  '이차돌': 'dining.restaurant',
  '하남돼지집': 'dining.restaurant',
  '명륜진사갈비': 'dining.restaurant',
  '황소곱창': 'dining.restaurant',
  '청기와타운': 'dining.restaurant',
  '삼겹살': 'dining.restaurant',

  // ── 대형마트 / 식료품 ──
  '이마트': 'grocery.supermarket',
  'emart': 'grocery.supermarket',
  '이마트에브리데이': 'grocery.supermarket',
  '홈플러스': 'grocery.supermarket',
  'homeplus': 'grocery.supermarket',
  '롯데마트': 'grocery.supermarket',
  '롯데슈퍼': 'grocery.supermarket',
  '코스트코': 'grocery.supermarket',
  'costco': 'grocery.supermarket',
  '농협하나로마트': 'grocery.supermarket',
  '하나로클럽': 'grocery.supermarket',
  '노브랜드': 'grocery.supermarket',
  '트레이더스': 'grocery.supermarket',
  '메가마트': 'grocery.supermarket',
  'ssg': 'grocery.supermarket',

  // ── 온라인 장보기 ──
  '마켓컬리': 'grocery.online_grocery',
  '컬리': 'grocery.online_grocery',
  '오아시스마켓': 'grocery.online_grocery',
  'b마트': 'grocery.online_grocery',
  '쿠팡로켓프레시': 'grocery.online_grocery',
  '네이버장보기': 'grocery.online_grocery',
  '헬로네이처': 'grocery.online_grocery',

  // ── 편의점 ──
  'cu': 'convenience_store',
  'gs25': 'convenience_store',
  '세븐일레븐': 'convenience_store',
  '7-eleven': 'convenience_store',
  '7eleven': 'convenience_store',
  '미니스톱': 'convenience_store',
  '이마트24': 'convenience_store',

  // ── 온라인 쇼핑 ──
  '쿠팡': 'online_shopping',
  'coupang': 'online_shopping',
  '네이버쇼핑': 'online_shopping',
  '네이버페이': 'online_shopping',
  '11번가': 'online_shopping',
  'g마켓': 'online_shopping',
  'gmarket': 'online_shopping',
  '옥션': 'online_shopping',
  'auction': 'online_shopping',
  '위메프': 'online_shopping',
  '티몬': 'online_shopping',
  '인터파크': 'online_shopping',
  '카카오쇼핑': 'online_shopping',
  '알리익스프레스': 'online_shopping',
  'aliexpress': 'online_shopping',
  '아마존': 'online_shopping',
  'amazon': 'online_shopping',
  '테무': 'online_shopping',
  'temu': 'online_shopping',
  '쉬인': 'online_shopping',
  'shein': 'online_shopping',
  '올리브영온라인': 'online_shopping',
  '카카오톡스토어': 'online_shopping',
  '톡딜': 'online_shopping',
  '직방': 'online_shopping',

  // ── 패션 / 의류 ──
  '무신사': 'fashion',
  'musinsa': 'fashion',
  '에이블리': 'fashion',
  '지그재그': 'fashion',
  '브랜디': 'fashion',
  '29cm': 'fashion',
  'wconcept': 'fashion',
  '더한섬': 'fashion',
  '유니클로': 'fashion',
  'uniqlo': 'fashion',
  '자라': 'fashion',
  'zara': 'fashion',
  'h&m': 'fashion',
  '나이키': 'fashion',
  'nike': 'fashion',
  '아디다스': 'fashion',
  'adidas': 'fashion',
  '뉴발란스': 'fashion',
  'abc마트': 'fashion',
  '크림': 'fashion',
  'kream': 'fashion',

  // ── 백화점 ──
  '롯데백화점': 'department_store',
  '현대백화점': 'department_store',
  '신세계백화점': 'department_store',
  'shinsegae': 'department_store',
  '갤러리아': 'department_store',
  '에이케이플라자': 'department_store',
  '더현대': 'department_store',
  '아울렛': 'offline_shopping',
  '프리미엄아울렛': 'offline_shopping',

  // ── 뷰티 / 화장품 ──
  '올리브영': 'offline_shopping',
  '시코르': 'offline_shopping',
  '롭스': 'offline_shopping',
  '이니스프리': 'offline_shopping',
  '아모레퍼시픽': 'offline_shopping',
  '다이소': 'offline_shopping',
  'daiso': 'offline_shopping',

  // ── 택시 ──
  '카카오택시': 'taxi',
  '카카오T': 'taxi',
  '카카오모빌리티': 'taxi',
  '타다': 'taxi',
  '우티': 'taxi',
  'ut': 'taxi',
  '아이엠택시': 'taxi',
  '택시': 'taxi',

  // ── 대중교통 ──
  '코레일': 'public_transit',
  'korail': 'public_transit',
  'srt': 'public_transit',
  'ktx': 'public_transit',
  '서울교통공사': 'public_transit',
  '지하철': 'public_transit',
  '버스': 'public_transit',
  '티머니': 'public_transit',
  '캐시비': 'public_transit',
  '레일플러스': 'public_transit',
  '고속버스': 'public_transit',
  '시외버스': 'public_transit',

  // ── 주유 ──
  'sk에너지': 'fuel',
  'sk주유소': 'fuel',
  'gs칼텍스': 'fuel',
  '현대오일뱅크': 'fuel',
  '에쓰오일': 'fuel',
  's-oil': 'fuel',
  '알뜰주유소': 'fuel',
  'ev충전': 'fuel',
  '충전소': 'fuel',
  '한국전력충전': 'fuel',

  // ── 주차 ──
  '주차': 'parking',
  '주차장': 'parking',
  '파킹클라우드': 'parking',
  '아이파킹': 'parking',
  '모두의주차장': 'parking',

  // ── 통행료 ──
  '하이패스': 'toll',
  '고속도로': 'toll',
  '한국도로공사': 'toll',

  // ── 영화 ──
  'cgv': 'movie',
  '롯데시네마': 'movie',
  '메가박스': 'movie',
  'megabox': 'movie',

  // ── 스트리밍 / 구독 ──
  '넷플릭스': 'streaming',
  'netflix': 'streaming',
  '유튜브프리미엄': 'streaming',
  'youtube premium': 'streaming',
  'youtube': 'streaming',
  '왓챠': 'streaming',
  '웨이브': 'streaming',
  'wavve': 'streaming',
  '시즌': 'streaming',
  '티빙': 'streaming',
  'tving': 'streaming',
  '디즈니플러스': 'streaming',
  'disney+': 'streaming',
  'disney plus': 'streaming',
  '애플tv': 'streaming',
  'apple tv': 'streaming',
  '스포티파이': 'streaming',
  'spotify': 'streaming',
  '멜론': 'streaming',
  '지니뮤직': 'streaming',
  '플로': 'streaming',
  '벅스': 'streaming',
  '밀리의서재': 'streaming',
  '리디북스': 'streaming',
  '리디': 'streaming',
  '쿠팡플레이': 'streaming',
  'coupang play': 'streaming',
  '아마존프라임': 'streaming',

  // ── 구독 / 멤버십 ──
  '쿠팡로켓와우': 'subscription',
  '네이버플러스멤버십': 'subscription',
  'ssg멤버십': 'subscription',

  // ── 게임 / 앱스토어 ──
  '구글플레이': 'entertainment',
  'google play': 'entertainment',
  '앱스토어': 'entertainment',
  'apple.com/bill': 'entertainment',
  '넥슨': 'entertainment',
  '엔씨소프트': 'entertainment',
  '넷마블': 'entertainment',
  '카카오게임즈': 'entertainment',
  '스팀': 'entertainment',
  'steam': 'entertainment',
  '플레이스테이션': 'entertainment',
  'playstation': 'entertainment',
  '닌텐도': 'entertainment',
  'nintendo': 'entertainment',

  // ── 통신 ──
  'skt': 'telecom',
  'sk텔레콤': 'telecom',
  'kt': 'telecom',
  'lg유플러스': 'telecom',
  'lgu+': 'telecom',
  '알뜰폰': 'telecom',
  '헬로모바일': 'telecom',
  'sk브로드밴드': 'telecom',
  'kt인터넷': 'telecom',
  'lg인터넷': 'telecom',

  // ── 보험 ──
  '삼성화재': 'insurance',
  '현대해상': 'insurance',
  'kb손해보험': 'insurance',
  '메리츠화재': 'insurance',
  '한화생명': 'insurance',
  '삼성생명': 'insurance',
  '교보생명': 'insurance',
  'db손해보험': 'insurance',
  '흥국화재': 'insurance',
  '라이나생명': 'insurance',

  // ── 병원 / 의료 ──
  '병원': 'hospital',
  '의원': 'hospital',
  '치과': 'hospital',
  '한의원': 'hospital',
  '안과': 'hospital',
  '피부과': 'hospital',
  '정형외과': 'hospital',
  '내과': 'hospital',
  '산부인과': 'hospital',
  '소아과': 'hospital',
  '이비인후과': 'hospital',
  '종합병원': 'hospital',
  '대학병원': 'hospital',
  '의료원': 'hospital',

  // ── 약국 ──
  '약국': 'pharmacy',
  '드럭스토어': 'pharmacy',

  // ── 교육 ──
  '학원': 'academy',
  '어학원': 'academy',
  '영어학원': 'academy',
  '수학학원': 'academy',
  '입시학원': 'academy',
  '태권도': 'academy',
  '피아노': 'academy',
  '음악학원': 'academy',
  '미술학원': 'academy',
  '운전면허': 'academy',
  '자동차학원': 'academy',

  // ── 온라인 교육 ──
  '클래스101': 'education',
  '패스트캠퍼스': 'education',
  '인프런': 'education',
  '에듀윌': 'education',
  '메가스터디': 'education',
  '이투스': 'education',
  '대성마이맥': 'education',

  // ── 도서 ──
  '교보문고': 'books',
  'kyobo': 'books',
  '알라딘': 'books',
  '예스24': 'books',
  'yes24': 'books',
  '영풍문고': 'books',
  '반디앤루니스': 'books',

  // ── 항공 ──
  '대한항공': 'airline',
  'korean air': 'airline',
  '아시아나': 'airline',
  'asiana': 'airline',
  '제주항공': 'airline',
  'jeju air': 'airline',
  '진에어': 'airline',
  'jin air': 'airline',
  '티웨이항공': 'airline',
  't\'way': 'airline',
  '에어서울': 'airline',
  '에어부산': 'airline',
  '에어프레미아': 'airline',
  '이스타항공': 'airline',

  // ── 숙박 ──
  '야놀자': 'hotel',
  '여기어때': 'hotel',
  'airbnb': 'hotel',
  '에어비앤비': 'hotel',
  '호텔스닷컴': 'hotel',
  'hotels.com': 'hotel',
  '부킹닷컴': 'hotel',
  'booking.com': 'hotel',
  '아고다': 'hotel',
  'agoda': 'hotel',
  '힐튼': 'hotel',
  '메리어트': 'hotel',
  '인터컨티넨탈': 'hotel',
  '롯데호텔': 'hotel',
  '신라호텔': 'hotel',

  // ── 여행 ──
  '하나투어': 'travel',
  '모두투어': 'travel',
  '노랑풍선': 'travel',
  '참좋은여행': 'travel',
  '클룩': 'travel',
  'klook': 'travel',
  '트립닷컴': 'travel',
  'trip.com': 'travel',
  '스카이스캐너': 'travel',

  // ── 공과금 / 관리비 ──
  '한국전력': 'utilities',
  '한전': 'utilities',
  '도시가스': 'utilities',
  '수도요금': 'utilities',
  '관리비': 'utilities',
  '아파트관리비': 'utilities',
  '국민건강보험': 'utilities',
  '국민연금': 'utilities',

  // ── 렌터카 / 차량 ──
  '쏘카': 'transportation',
  'socar': 'transportation',
  '그린카': 'transportation',
  '카카오T렌터카': 'transportation',
  '롯데렌터카': 'transportation',
  'sk렌터카': 'transportation',

  // ── 반려동물 ──
  '펫프렌즈': 'offline_shopping',
  '바잇미': 'offline_shopping',
  '동물병원': 'medical',

  // ── 헬스 / 피트니스 ──
  '헬스장': 'entertainment',
  '피트니스': 'entertainment',
  '요가': 'entertainment',
  '필라테스': 'entertainment',
  '골프': 'entertainment',
  '골프장': 'entertainment',
  '스크린골프': 'entertainment',

  // ── 놀이공원 / 레저 ──
  '에버랜드': 'entertainment',
  '롯데월드': 'entertainment',
  '워터파크': 'entertainment',
  '스키장': 'entertainment',
  '놀이공원': 'entertainment',
  '키자니아': 'entertainment',

  // ── 세탁 ──
  '세탁': 'offline_shopping',
  '크린토피아': 'offline_shopping',
  '런드리고': 'offline_shopping',

  // ── 인테리어 / 가전 ──
  '이케아': 'offline_shopping',
  'ikea': 'offline_shopping',
  '한샘': 'offline_shopping',
  '삼성전자': 'offline_shopping',
  '하이마트': 'offline_shopping',
  '전자랜드': 'offline_shopping',
  '쿠쿠': 'offline_shopping',
  'lg전자': 'offline_shopping',
  '애플': 'offline_shopping',
  'apple': 'offline_shopping',
};
